FORT = gfortran-7

algen_dir = ../ALGEN
chlsk_dir = ../CHLSK
digis_dir = ../DIGIS
fftw3_dir = ../FFTW3
gplot_dir = ../GPLOT
intpl_dir = ../INTPL
minim_dir = ../MINIM
msolv_dir = ../MSOLV
randm_dir = ../RANDM
splin_dir = ../SPLIN
tchev_dir = ../TCHEV
utils_dir = ../UTILS

