main – MUSST
main Program
98 statements
Source File
Uses
omp_lib
test_musst
data_arch
num_param
solver
Subroutine to run a test with MUSST
Calls
Contents
Variables
prg_arg job_file date time repos archive
Subroutines
read_config
Source Code
main
Variables
Type Attributes Name Initial
character(len=128) :: prg_arg
character(len=128) :: job_file
character(len=8) :: date
character(len=10) :: time
character(len=15) :: repos
integer(kind=I4) :: archive
Subroutines
subroutine read_config()
Arguments
None
Source Code
program main
use omp_lib
use test_musst
use data_arch,  only : I4, NB_THREADS_MAX, OUT_U=>OPU, get_unit
use num_param,  only : VERBOSE, OUTPUT_FILE, OPU
use solver,     only : SOLVER_BS, SOLVER_TS, SOLV_MESS
implicit none
character(len=128) :: prg_arg
character(len=128) :: job_file
character(len= 8) :: date
character(len=10) :: time
character(len=15) :: repos
integer(kind=I4)  :: archive
! a result directory is created under "/out" with the date as name
! ----------------------------------------------------------------
call date_and_time(date, time)
repos = date//'_'//time(1:6)
call execute_command_line("mkdir out/"//repos, wait=.true.)
! the job file is the program argument
! ------------------------------------
prg_arg  = repeat(' ', len(prg_arg))
job_file = repeat(' ', len(job_file))
call get_command_argument(1, prg_arg)     ! argument one: job file
if (len_trim(prg_arg) == 0) then          ! if there is no job file, stop
   stop 'no job file, stop'
else
   job_file = trim(adjustl(prg_arg))
endif
! the job file is copied in the result directory
! ----------------------------------------------
call execute_command_line("cp "//trim(job_file)//" out/"//repos, wait=.true.)
! the job file is processed
! -------------------------
call read_config
call run_test
if (OPU/=OUT_U) close(OPU)
stop
contains
   subroutine read_config()
   implicit none
      integer(kind=I4)   :: jf, err_read
      character(len=032) :: word
      character(len=128) :: job_copy
      job_copy = "out/"//repos//job_file(4:len_trim(job_file))
      VERBOSE   = 20
      SOLV_MESS = 0
      OPU = 0
      OUTPUT_FILE = "no_file"
      SOLVER_BS = 3
      SOLVER_TS = 2
      NB_THREADS_MAX = -1
      archive = 0
      test_num = 0
      call get_unit(jf) ; open(jf, file = trim(job_file), status = 'old')
         do
            word = repeat(' ', len(word))
            read(jf, *, iostat = err_read) word
            if ( index(word, 'END_FILE'      ) /= 0 ) exit
            if ( index(word, 'VERBOSE'       ) /= 0 ) then
               read(jf, *) VERBOSE
            endif
            if ( index(word, 'SOLV_MESS'     ) /= 0 ) then
               read(jf, *) SOLV_MESS
            endif
            if ( index(word, 'OUTPUT_UNIT'   ) /= 0 ) then
               read(jf, *) OPU
               if (OPU==0) then
                  OPU = OUT_U
               else
                  read(jf, *) OUTPUT_FILE
                  call get_unit(OPU)
                  open(unit = OPU,                                               &
                       file = "out/"//repos//"/"//trim(adjustl(OUTPUT_FILE)),    &
                     status = 'unknown')
               endif
            endif
            if ( index(word, 'SOLVER_BS'     ) /= 0 ) then
               read(jf, *) SOLVER_BS
               if (SOLVER_BS==1) stop "some remaining problems with SuLU, choose '3' instead"
               if (SOLVER_BS==2) stop "MUMPS is multithreaded, it is designed for TS, choose '3' instead"
            endif
            if ( index(word, 'SOLVER_TS'     ) /= 0 ) then
               read(jf, *) SOLVER_TS
            endif
            if ( index(word, 'PROBLEM_TYPE'  ) /= 0 ) then
               read(jf, *) test_num
            endif
            if ( index(word, 'PARAM_MUSST'   ) /= 0 ) then
               call read_data(jf, repos)
            endif
            if ( index(word, 'NB_THREADS_MAX') /= 0 ) then
               read(jf, *) NB_THREADS_MAX
               if (NB_THREADS_MAX<0) then
                  !$ NB_THREADS_MAX = omp_get_num_procs()
               endif
            endif
            if ( index(word, 'ARCHIVE') /= 0 ) then
               read(jf, *) archive
               if (ARCHIVE==1) then
                  call execute_command_line("sh bin/save/save.sh", wait=.true.)
                  call execute_command_line("mv *.7z out/"//repos//"/")
               endif
            endif
         enddo
      close(jf)
   return
   endsubroutine read_config
endprogram main
Call graph
main calls run_test, read_config
run_test calls get_unit, test_bearing_x_fe, test_slider_ms, test_pocket_fe, test_rough_fe, test_rough_ms, test_slider_fe, test_bearing_y_fe
read_config calls get_unit, read_data
test_bearing_x_fe calls modify_h_bearing, init_fe_prob, solve_fe_prob
read_data calls num_par
test_slider_ms calls modify_h_slider_ms, solve_ms_prob, init_ms_prob
test_pocket_fe calls init_fe_prob, solve_fe_prob, modify_h_pocket
test_rough_fe calls init_fe_prob, solve_fe_prob, init_rough_prob, apply_roughness
test_rough_ms calls apply_roughness_ms, solve_ms_prob, init_rough_prob, init_ms_prob
test_slider_fe calls modify_h_slider, init_fe_prob, solve_fe_prob
test_bearing_y_fe calls init_fe_prob, solve_fe_prob, modify_h_bearing_y
modify_h_slider_ms calls modify_h_slider
apply_roughness_ms calls apply_roughness
init_fe_prob calls create_rect_fe_film
solve_ms_prob calls ms_fe_f_2_mat, multi_scale_solve_fe_film, save_ms_field
solve_fe_prob calls save_fe_field, compute_corner_fluxes, solve_fe_film
init_ms_prob calls multi_scale_create_rect_fe_film
create_rect_fe_film calls create_rect_x_ymesh
save_fe_field calls write_surf, empty, init_scal
multi_scale_solve_fe_film calls solve_fe_film, solve_syst, convert_matrice_format, multi_scale_assembly_fe_film_reynolds, omp_get_thread_num, apply_bc_fe_film_simple
save_ms_field calls ms_fe_f_2_mat, write_surf, empty, init_scal
compute_corner_fluxes calls assembly_fe_film_reynolds
multi_scale_create_rect_fe_film calls create_rect_fe_film
solve_fe_film calls solve_syst, convert_matrice_format, omp_get_thread_num, apply_bc_fe_film, assembly_fe_film_reynolds, apply_bc_fe_film_simple
solve_syst calls close_solver, init_solver, solution_solver, analyse_solver, factorize_solver, freefact_solver
convert_matrice_format calls from_elemental_to_assembled
multi_scale_assembly_fe_film_reynolds calls omp_get_thread_num
assembly_fe_film_reynolds calls assemble_in_mat_sol, elementary_assembly_fe_film_reynolds
write_surf calls get_unit, scal2surf, lower, surf2scal
init_scal calls empty
close_solver calls umfpack_di_free_symbolic, umfpack_di_report_info, close_superlu, dmumps, mpi_finalize, umfpack_di_free_numeric, ma48_finalize
init_solver calls umfpack_di_defaults, dmumps, mpi_finalize, init_superlu, ma48_initialize, umfpack_di_report_control, mpi_init
solution_solver calls s_umfpack_di_solve, solv_superlu, dmumps, mpi_finalize, ma48_solve
surf2scal calls c_f_string
analyse_solver calls ma48_analyse, dmumps, prep_superlu, s_umfpack_di_symbolic
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
factorize_solver calls dmumps, umfpack_di_free_numeric, s_umfpack_di_numeric, ma48_factorize
freefact_solver calls umfpack_di_free_numeric, free_superlu
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
s_umfpack_di_solve calls umfpack_di_solve
close_superlu calls destroy_dense_matrix, destroy_compcol_matrix
solv_superlu calls prep_superlu, statinit, dgssvx, destroy_supernode_matrix, destroy_compcol_matrix, statfree
compute_prc_tables_reynolds_supg calls ni4_up_2d, dj4, length_width_elem
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
init_superlu calls set_default_options
prep_superlu calls dcreate_compcol_matrix, dcreate_dense_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
c_f_string calls empty
umfpack_di_report_control calls c_umfpack_di_report_control
ni4_up_2d calls ni4_up_1d
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic