analyse_solver – MUSST
analyse_solver Subroutine
43 statements
Source File
private subroutine analyse_solver(mat)
Note
Subroutine to analyse, factorize (symbolic) the matrix of the system
Arguments
Type Intent Optional Attributes Name
type(MAT_SOLV), intent(inout), target :: mat
high level system type
Calls
Called by
Contents
Source Code
analyse_solver
Source Code
   subroutine analyse_solver(mat)
   implicit none
   type(MAT_SOLV), intent(inout), target :: mat   !! *high level system type*
      select case(mat%slv_t)
         case(MA48)
#if WITH_MA48
            mat%matma48%zmat%row => mat%irow
            mat%matma48%zmat%col => mat%jcol
            mat%matma48%zmat%val => mat%a_elt
            mat%matma48%zmat%n   = mat%nn
            mat%matma48%zmat%m   = mat%nn
            mat%matma48%zmat%ne  = mat%nz
            call ma48_analyse(matrix = mat%matma48%zmat, &
                             factors = mat%matma48%fact, &
                             control = mat%matma48%ctrl, &
                               ainfo = mat%matma48%ainf, &
                               finfo = mat%matma48%finf)
            if (mat%matma48%ainf%flag < 0) then
               write(OPU,*) 'Failure of ma48_analyse with ainfop%flag = ', mat%matma48%ainf%flag
               stop
            endif
#else
   stop 'MA48_LIB not defined'
#endif
         case(MUMP)
            mat%matmump%eltptr   => mat%eltptr
            mat%matmump%eltvar   => mat%eltvar
            mat%matmump%a_elt    => mat%a_elt
            mat%matmump%rhs      => mat%b
            mat%matmump%n    = mat%nn
            mat%matmump%nelt = mat%ne
            mat%matmump%job = 1 ! performs the analysis
            call dmumps(mat%matmump)
         case(SULU)
            mat%matsulu%irow   => mat%irow
            mat%matsulu%jptr   => mat%jptr
            mat%matsulu%a_elt  => mat%a_elt
            mat%matsulu%b      => mat%b
            mat%matsulu%n     = mat%nn
            mat%matsulu%nz    = mat%nz
            mat%matsulu%nrhs  = 1
            mat%matsulu%first = .true.
            call prep_superlu(sulu = mat%matsulu)
         case(UMFP)
            call s_umfpack_di_symbolic(n_row    = mat%nn,                  &
                                       n_col    = mat%nn,                  &
                                       Ap       = mat%jptr,                &
                                       Ai       = mat%irow,                &
                                       Ax       = mat%a_elt,               &
                                       Symbolic = mat%matumfp%c_symbolic,  &
                                       Control  = mat%matumfp%c_control,   &
                                       Info     = mat%matumfp%c_info)
         case default
            stop 'ANALYSE_SOLVER : unknown solver type'
      endselect
   return
   endsubroutine analyse_solver
Call graph
analyse_solver calls prep_superlu, dmumps, s_umfpack_di_symbolic, ma48_analyse
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_di_symbolic calls c_umfpack_di_symbolic
solve_syst calls analyse_solver
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_fe_prob calls solve_fe_film
test_rough_fe calls solve_fe_prob
test_bearing_x_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
run_test calls test_rough_fe, test_bearing_x_fe, test_pocket_fe, test_bearing_y_fe, test_rough_ms, test_slider_fe, test_slider_ms
main calls run_test