assembly_FE_film_reynolds – MUSST
assembly_FE_film_reynolds Subroutine
27 statements
Source File
public subroutine assembly_FE_film_reynolds(fe_f, mat, ass_c)
Note
Subroutine to to solve a FE_FILM
Arguments
Type Intent Optional Attributes Name
type(FE_FILM), intent(inout) :: fe_f
FE_film data type
type(MAT_SOLV), intent(inout) :: mat
matrices for solving
integer(kind=I4), intent(in) :: ass_c
assembly type
Calls
Called by
Contents
Source Code
assembly_FE_film_reynolds
Source Code
   subroutine assembly_FE_film_reynolds(fe_f, mat, ass_c)
   implicit none
   type(FE_FILM),    intent(inout) :: fe_f     !! *FE_film data type*
   type(MAT_SOLV),   intent(inout) :: mat      !! *matrices for solving*
   integer(kind=I4), intent(in)    :: ass_c    !! *assembly type*
      integer(kind=I4), dimension(2)                :: compt
      integer(kind=I4), dimension(MAX_NNE)          :: tind4
      real(kind=R8),    dimension(MAX_NNE)          :: b4
      real(kind=R8),    dimension(MAX_NNE, MAX_NNE) :: k4
      integer(kind=I4) :: e, i, ii, el_t, el_n
      ! assembly
      compt(1:2) = 1
      mat%b = 0._R8
      do e = 1, fe_f%m%ne
         call elementary_assembly_FE_film_reynolds(fe_f = fe_f,   & !
                                                  ke_ij = k4,     & ! elementary matrix         : OUT
                                                   be_i = b4,     & ! elementary rhs member     : OUT
                                                  ind_e = tind4,  & ! elementary index member   : OUT
                                                      e = e,      & ! element number
                                                  ass_c = ass_c)    ! assembly type
         do i = 1, 4
            ii = tind4(i)
            mat%b(ii) = mat%b(ii) + b4(i)
         enddo
         el_t = fe_f%m%el_t(e)
         el_n = fe_f%m%el_n(e)
         ! assembly of the elemental matrix in the solver matrix
         if (ass_c == ASS) then
            call assemble_in_mat_sol(mat = mat,    &
                                     num = e,      &
                                    nelt = el_t,   &
                                   nline = el_n,   &
                                    tind = tind4,  &
                                   m_elt = k4,     &
                                   compt = compt)
         endif
      enddo
      if (ass_c == ASS) mat%eltptr(1) = 1
   return
   endsubroutine assembly_FE_film_reynolds
Call graph
assembly_fe_film_reynolds calls elementary_assembly_fe_film_reynolds, assemble_in_mat_sol
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
compute_prc_tables_reynolds_supg calls length_width_elem, dj4, ni4_up_2d
ni4_up_2d calls ni4_up_1d
solve_fe_film calls assembly_fe_film_reynolds
compute_corner_fluxes calls assembly_fe_film_reynolds
elementary_full_domain_fe_film_reynolds calls solve_fe_film, compute_corner_fluxes
multi_scale_solve_fe_film calls solve_fe_film
solve_fe_prob calls solve_fe_film, compute_corner_fluxes
test_bearing_x_fe calls solve_fe_prob
solve_ms_prob calls multi_scale_solve_fe_film
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_ms calls solve_ms_prob
run_test calls test_bearing_x_fe, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe, test_rough_ms, test_slider_ms
read_config calls run_test
main calls read_config