assemble_in_mat_sol – MUSST
assemble_in_mat_sol Subroutine
24 statements
Source File
public subroutine assemble_in_mat_sol(mat, num, nelt, nline, tind, m_elt, compt)
Note
Subroutine to assemble elemental matrices in the solver matrices
Arguments
Type Intent Optional Attributes Name
type(MAT_SOLV), intent(inout) :: mat
mat_solv type
integer(kind=I4), intent(in) :: num
element number
integer(kind=I4), intent(in) :: nelt
size of elemental matrix
integer(kind=I4), intent(in) :: nline
number of lines
integer(kind=I4), intent(in), dimension(nelt) :: tind
index table of elemental matrix
real(kind=R8), intent(in), dimension(nelt, nelt) :: m_elt
elemental matrix
integer(kind=I4), intent(inout), dimension(2) :: compt
number to index the position in the solver matrix
Called by
Contents
Source Code
assemble_in_mat_sol
Source Code
   subroutine assemble_in_mat_sol(mat, num, nelt, nline, tind, m_elt, compt)
   implicit none
   type(MAT_SOLV),   intent(inout)                        :: mat     !! *mat_solv type*
   integer(kind=I4), intent(in   )                        :: num     !! *element number*
   integer(kind=I4), intent(in   )                        :: nelt    !! *size of elemental matrix*
   integer(kind=I4), intent(in   )                        :: nline   !! *number of lines*
   integer(kind=I4), intent(in   ), dimension(nelt)       :: tind    !! *index table of elemental matrix*
   real(kind=R8),    intent(in   ), dimension(nelt, nelt) :: m_elt   !! *elemental matrix*
   integer(kind=I4), intent(inout), dimension(2)          :: compt   !! *number to index the position in the solver matrix*
      integer(kind=I4) :: i, j
      ! check compt
      if (compt(2) > mat%nt) stop 'compt > matrix size in assemble_in_mat_sol'
      do j = 1, nline
         mat%eltvar(compt(1)) = tind(j)
         compt(1) = compt(1) +1
      enddo
      mat%eltptr(num+1) = compt(1)
      do j = 1, nelt
         do i = 1, nelt
            mat%a_elt(compt(2)) = m_elt(i, j)
            compt(2) = compt(2) + 1
         enddo
      enddo
   return
   endsubroutine assemble_in_mat_sol
Call graph
assembly_fe_film_reynolds calls assemble_in_mat_sol
compute_corner_fluxes calls assembly_fe_film_reynolds
solve_fe_film calls assembly_fe_film_reynolds
multi_scale_solve_fe_film calls solve_fe_film
elementary_full_domain_fe_film_reynolds calls compute_corner_fluxes, solve_fe_film
solve_fe_prob calls compute_corner_fluxes, solve_fe_film
test_bearing_x_fe calls solve_fe_prob
solve_ms_prob calls multi_scale_solve_fe_film
test_pocket_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
run_test calls test_bearing_x_fe, test_pocket_fe, test_rough_fe, test_slider_fe, test_bearing_y_fe, test_rough_ms, test_slider_ms
test_rough_ms calls solve_ms_prob
test_slider_ms calls solve_ms_prob
main calls run_test