c_f_string – MUSST
c_f_string Subroutine
23 statements
Source File
private subroutine c_f_string(cs, fs, borne_s)
Note
Converts a C string to a Fortran string
A From a memory viewpoint, a C string is like a character vector ending with a C_NULL_CHAR, so as long as it is not found, the characters are copied one by one in a fortran string
Arguments
Type Intent Optional Attributes Name
character(kind=C_CHAR), intent(in), dimension(:) :: cs
C string
character(len=*), intent(out) :: fs
Fortran string
integer(kind=I4), intent(out) :: borne_s
resulting Fortran string length
Calls
Called by
Contents
Source Code
c_f_string
Source Code
   subroutine c_f_string(cs, fs, borne_s)
   implicit none
   character(kind=C_CHAR), dimension(:), intent(in) :: cs   !! *C string*
   character(len=*), intent(out) :: fs                      !! *Fortran string*
   integer(kind=I4), intent(out) :: borne_s                 !! *resulting Fortran string length*
      integer(kind=I4) :: i, ucs
      ucs = size(cs) ! vector length
      borne_s = ucs  ! resulting string default length
      i = 1
      do
         if (i>ucs) exit
         if (cs(i)==C_NULL_CHAR) then  ! fin de chaîne c rencontrée ; s'il n'y a pas de null_char
            borne_s = i-1              ! c'est qu'on utilise tout le vecteur
            exit
         endif
         i = i + 1
      enddo
      call empty(fs)
      do i = 1, borne_s ! the C string is translated into fortran
         fs(i:i) = cs(i)
      enddo
   return
   endsubroutine c_f_string
Call graph
c_f_string calls empty
trans_surf_txt calls c_f_string
surf2scal calls c_f_string
write_surf calls surf2scal
open_surffile calls surf2scal
save_fe_field calls write_surf
save_ms_field calls write_surf
solve_ms_prob calls save_ms_field
solve_fe_prob calls save_fe_field
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config