dj4 – MUSST
dj4 Function
24 statements
Source File
public function dj4(ksi, eta, x, y)
Note
Jacobian calculated without calling any function, for computing speed reasons.
Note
Maxima, Wxmaxima script
ni4_1(xi, eta):= (1. -xi)*(1. -eta)/4.$
ni4_2(xi, eta):= (1. +xi)*(1. -eta)/4.$
ni4_3(xi, eta):= (1. +xi)*(1. +eta)/4.$
ni4_4(xi, eta):= (1. -xi)*(1. +eta)/4.$
ni4xi_1(xi, eta):=diff(ni4_1(xi, eta),xi,1)$
ni4xi_2(xi, eta):=diff(ni4_2(xi, eta),xi,1)$
ni4xi_3(xi, eta):=diff(ni4_3(xi, eta),xi,1)$
ni4xi_4(xi, eta):=diff(ni4_4(xi, eta),xi,1)$
ni4eta_1(xi, eta):=diff(ni4_1(xi, eta),eta,1)$
ni4eta_2(xi, eta):=diff(ni4_2(xi, eta),eta,1)$
ni4eta_3(xi, eta):=diff(ni4_3(xi, eta),eta,1)$
ni4eta_4(xi, eta):=diff(ni4_4(xi, eta),eta,1)$
j4_1(xi, eta):=factorsum(ni4xi_1(xi, eta)*x1+ni4xi_2(xi, eta)*x2+ni4xi_3(xi, eta)*x3+ni4xi_4(xi, eta)*x4)$
j4_1(xi, eta);
j4_2(xi, eta):=factorsum(ni4xi_1(xi, eta)*y1+ni4xi_2(xi, eta)*y2+ni4xi_3(xi, eta)*y3+ni4xi_4(xi, eta)*y4)$
j4_2(xi, eta);
j4_3(xi, eta):=factorsum(ni4eta_1(xi, eta)*x1+ni4eta_2(xi, eta)*x2+ni4eta_3(xi, eta)*x3+ni4eta_4(xi, eta)*x4)$
j4_3(xi, eta);
j4_4(xi, eta):=factorsum(ni4eta_1(xi, eta)*y1+ni4eta_2(xi, eta)*y2+ni4eta_3(xi, eta)*y3+ni4eta_4(xi, eta)*y4)$
j4_4(xi, eta);
dj4(xi, eta):=factorout(j4_1(xi, eta)*j4_4(xi, eta)-j4_2(xi, eta)*j4_3(xi, eta),xi,eta)$
dj4(xi, eta);
ni4x_1(xi,eta):=factorout(j4_4(xi, eta)*ni4xi_1(xi, eta),eta,xi) - factorout(j4_3(xi, eta)*ni4eta_1(xi, eta),xi,eta)$
ni4x_1(xi,eta);
ni4x_2(xi,eta):=factorout(j4_4(xi, eta)*ni4xi_2(xi, eta),eta,xi) - factorout(j4_3(xi, eta)*ni4eta_2(xi, eta),eta,xi)$
ni4x_2(xi,eta);
ni4x_3(xi,eta):=factorout(j4_4(xi, eta)*ni4xi_3(xi, eta),eta,xi) - factorout(j4_3(xi, eta)*ni4eta_3(xi, eta),xi,eta)$
ni4x_3(xi,eta);
ni4x_4(xi,eta):=factorout(j4_4(xi, eta)*ni4xi_4(xi, eta),eta,xi) - factorout(j4_3(xi, eta)*ni4eta_4(xi, eta),eta,xi)$
ni4x_4(xi,eta);
ni4y_1(xi,eta):=factorout(-j4_2(xi, eta)*ni4xi_1(xi, eta),eta,xi) + factorout(j4_1(xi, eta)*ni4eta_1(xi, eta),xi,eta)$
ni4y_1(xi,eta);
ni4y_2(xi,eta):=factorout(-j4_2(xi, eta)*ni4xi_2(xi, eta),eta,xi) + factorout(j4_1(xi, eta)*ni4eta_2(xi, eta),eta,xi)$
ni4y_2(xi,eta);
ni4y_3(xi,eta):=factorout(-j4_2(xi, eta)*ni4xi_3(xi, eta),eta,xi) + factorout(j4_1(xi, eta)*ni4eta_3(xi, eta),xi,eta)$
ni4y_3(xi,eta);
ni4y_4(xi,eta):=factorout(-j4_2(xi, eta)*ni4xi_4(xi, eta),eta,xi) + factorout(j4_1(xi, eta)*ni4eta_4(xi, eta),eta,xi)$
ni4y_4(xi,eta);
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: ksi
real(kind=R8), intent(in) :: eta
real(kind=R8), intent(in), dimension(4) :: x
real(kind=R8), intent(in), dimension(4) :: y
Return Value real(kind=R8)
Called by
Contents
None
Call graph
compute_prc_tables_reynolds_supg calls dj4
fx calls compute_prc_tables_reynolds_supg
fy calls compute_prc_tables_reynolds_supg
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
fz calls compute_prc_tables_reynolds_supg
assembly_fe_film_reynolds calls elementary_assembly_fe_film_reynolds
solve_fe_film calls assembly_fe_film_reynolds
compute_corner_fluxes calls assembly_fe_film_reynolds
elementary_full_domain_fe_film_reynolds calls solve_fe_film, compute_corner_fluxes
multi_scale_solve_fe_film calls solve_fe_film
solve_fe_prob calls solve_fe_film, compute_corner_fluxes
test_bearing_x_fe calls solve_fe_prob
solve_ms_prob calls multi_scale_solve_fe_film
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_ms calls solve_ms_prob
run_test calls test_bearing_x_fe, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe, test_rough_ms, test_slider_ms
read_config calls run_test
main calls read_config