elementary_full_domain_FE_film_reynolds – MUSST
elementary_full_domain_FE_film_reynolds Subroutine
61 statements
Source File
public subroutine elementary_full_domain_FE_film_reynolds(fe_f, mat, ke_ij, be_i, ind_e)
Note
Calculate the elementary matrices on a full domain
Arguments
Type Intent Optional Attributes Name
type(FE_FILM), intent(inout) :: fe_f
FE film
type(MAT_SOLV), intent(inout) :: mat
solver type matrices
real(kind=R8), intent(out), dimension(MAX_NNC, MAX_NNC) :: ke_ij
elementary matrix
real(kind=R8), intent(inout), dimension(MAX_NNC) :: be_i
elementary rhs member
integer(kind=I4), intent(out), dimension(MAX_NNC) :: ind_e
elementary index member
Calls
Contents
Source Code
elementary_full_domain_FE_film_reynolds
Source Code
   subroutine elementary_full_domain_FE_film_reynolds(fe_f, mat, ke_ij, be_i, ind_e)
   implicit none
   type(FE_FILM),    intent(inout)                              :: fe_f   !! *FE film*
   type(MAT_SOLV),   intent(inout)                              :: mat    !! *solver type matrices*
   real(kind=R8),    intent(out  ), dimension(MAX_NNC, MAX_NNC) :: ke_ij  !! *elementary matrix*
   real(kind=R8),    intent(inout), dimension(MAX_NNC         ) :: be_i   !! *elementary rhs member*
   integer(kind=I4), intent(out  ), dimension(MAX_NNC         ) :: ind_e  !! *elementary index member*
      integer(kind=I4) :: e, ee, i, j, ii, nbc, nc
      logical(kind=I4) :: flag
      integer(kind=I4), dimension(MAX_NBS) :: ind_n
      real(kind=R8),    dimension(MAX_NBS) :: sav_vn
      real(kind=R8),    dimension(MAX_NNC) :: bc, dp
      nc = fe_f%m%nc
      ! check of precomputed tables allocation
      if (.not.allocated(fe_f%prc%vcal)) call init_prc_tab(fe_f)
      ! boundary condition initialization
      if (BC_SPLINE) then
         bc(1:nc)  = 0
      else
         bc(1:nc) = be_i(1:nc)
      endif
      j = 1
      do e = 1, fe_f%m%ned
      do ee = 1, fe_f%m%ed(e)%n
         ind_n(j)  = fe_f%m%ed(e)%nm(ee)
         sav_vn(j) = fe_f%vn(ind_n(j), P_N)
         j = j +1
      enddo
      enddo
      nbc = j -1
      ! matrices
      ke_ij = 0._R8
      ind_e = 0
      be_i  = 0._R8
      ! calculation of the elementary matrix
      do i = 1, nc ! number of corners
         ii = fe_f%m%cor(i)
         ind_e(i) = ii
         dp(i) = fe_f%vn(ii, P_N)/1000
         if (BC_SPLINE) then
            bc(i) = dp(i)
         else
            bc(i) = bc(i) + dp(i)
         endif
         if (i==1) flag = .true.
         call solve_FE_film(fe_f = fe_f,     &  !
                             mat = mat,      &  !
                              bc = bc,       &  ! in
                        flag_ass = flag)        !
         flag = .false.
         call compute_corner_fluxes(fe_f = fe_f,      &  !
                                     mat = mat,       &  !
                                      bf = be_i)         ! out
         ke_ij(1:nc, i) = - be_i(1:nc) / dp(i)
         if (BC_SPLINE) then
            bc(i) = 0
         else
            bc(i) = bc(i) -dp(i)
         endif
         do j = 1, nbc
            fe_f%vn(ind_n(j), P_N) = sav_vn(j)
         enddo
      enddo
      ! calculation of the RHS table
      call solve_FE_film(fe_f = fe_f,     &  !
                          mat = mat,      &  !
                           bc = bc,       &  !
                     flag_ass = .false.)     !
      call compute_corner_fluxes(fe_f = fe_f,      &  !
                                  mat = mat,       &  !
                                   bf = be_i)         ! out
      ! update of the matrix: the derivative is the difference
      ! between the residuals divided by the delta p
      do i = 1, nc
         ke_ij(1:nc, i) = ke_ij(1:nc, i) + be_i(1:nc)/dp(i)
      enddo
   return
   endsubroutine elementary_full_domain_FE_film_reynolds
Call graph
elementary_full_domain_fe_film_reynolds calls compute_corner_fluxes, solve_fe_film
compute_corner_fluxes calls assembly_fe_film_reynolds
solve_fe_film calls solve_syst, convert_matrice_format, omp_get_thread_num, assembly_fe_film_reynolds, apply_bc_fe_film_simple, apply_bc_fe_film
solve_syst calls close_solver, init_solver, solution_solver, analyse_solver, factorize_solver, freefact_solver
convert_matrice_format calls from_elemental_to_assembled
assembly_fe_film_reynolds calls assemble_in_mat_sol, elementary_assembly_fe_film_reynolds
close_solver calls umfpack_di_free_symbolic, umfpack_di_report_info, close_superlu, dmumps, mpi_finalize, umfpack_di_free_numeric, ma48_finalize
init_solver calls umfpack_di_defaults, dmumps, mpi_finalize, init_superlu, ma48_initialize, umfpack_di_report_control, mpi_init
solution_solver calls s_umfpack_di_solve, solv_superlu, dmumps, mpi_finalize, ma48_solve
analyse_solver calls ma48_analyse, dmumps, prep_superlu, s_umfpack_di_symbolic
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
factorize_solver calls dmumps, umfpack_di_free_numeric, s_umfpack_di_numeric, ma48_factorize
freefact_solver calls umfpack_di_free_numeric, free_superlu
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
s_umfpack_di_solve calls umfpack_di_solve
close_superlu calls destroy_dense_matrix, destroy_compcol_matrix
solv_superlu calls prep_superlu, statinit, dgssvx, destroy_supernode_matrix, destroy_compcol_matrix, statfree
compute_prc_tables_reynolds_supg calls ni4_up_2d, dj4, length_width_elem
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
init_superlu calls set_default_options
prep_superlu calls dcreate_compcol_matrix, dcreate_dense_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
ni4_up_2d calls ni4_up_1d
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic