empty – MUSST
empty Subroutine
6 statements
Source File
public subroutine empty(charinout)
Note
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: charinout
Called by
Contents
Source Code
empty
Source Code
   subroutine empty(charinout)
   implicit none
   character(len=*), intent(inout) :: charinout
      charinout = repeat(' ', len(charinout))
   return
   endsubroutine empty
Call graph
save_fe_field calls empty, init_scal, write_surf
save_ms_field calls empty, init_scal, write_surf
c_f_string calls empty
init_scal calls empty
trans_surf_txt calls empty, c_f_string
solve_ms_prob calls save_ms_field
solve_fe_prob calls save_fe_field
surf2scal calls c_f_string
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
open_surffile calls surf2scal
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
write_surf calls surf2scal
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config