free_superlu – MUSST
free_superlu Subroutine
4 statements
Source File
public subroutine free_superlu()
Note
Subroutine that actually does nothing yet. Maybe, there will be extra memory that could be released here?
Arguments
None
Called by
Contents
Source Code
free_superlu
Source Code
   subroutine free_superlu()
   implicit none
   !type(SULU_ENV), intent(inout) :: sulu
   return
   endsubroutine free_superlu
Call graph
freefact_solver calls free_superlu
solve_syst calls freefact_solver
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_fe_prob calls solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
test_slider_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
test_pocket_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
run_test calls test_slider_fe, test_rough_ms, test_bearing_x_fe, test_bearing_y_fe, test_slider_ms, test_pocket_fe, test_rough_fe
main calls run_test