fx – MUSST
fx Function
11 statements
Source File
private function fx(fe_f)
Note
function to calculate the friction force along in a fluid film
Arguments
Type Intent Optional Attributes Name
class(FE_FILM), intent(inout) :: fe_f
FE film
Return Value real(kind=R8)
Calls
Contents
None
Call graph
fx calls compute_prc_tables_reynolds_supg
compute_prc_tables_reynolds_supg calls length_width_elem, dj4, ni4_up_2d
ni4_up_2d calls ni4_up_1d