init_rough_prob – MUSST
init_rough_prob Subroutine
7 statements
Source File
private subroutine init_rough_prob()
Note
Subroutine to initialize a deterministic 'rough' problem
Arguments
None
Called by
Contents
Source Code
init_rough_prob
Source Code
   subroutine init_rough_prob
   implicit none
      allocate(tab_s(nx, ny))
      tab_s = 0._R8
      call read_surf(nom_fic=trim(surface_file), mu=1._R8, sq=sq, tab_s=tab_s, scal=scal_tmp)
   return
   endsubroutine init_rough_prob
Call graph
test_rough_fe calls init_rough_prob
test_rough_ms calls init_rough_prob
run_test calls test_rough_fe, test_rough_ms
main calls run_test