init_fe_prob – MUSST
init_fe_prob Subroutine
15 statements
Source File
private subroutine init_fe_prob()
Note
Subroutine to initialize a deterministic 'smooth' problem
Arguments
None
Calls
Called by
Contents
Source Code
init_fe_prob
Source Code
   subroutine init_fe_prob
   implicit none
      if (mod(nx, 2) /= 1) then
         write(OPU,*) 'It is better to use an odd number of nodes in the x dir to have profile for comparison with analytical sol.'
      endif
      fe_f%m%nx = nx
      fe_f%m%ny = ny
      fe_f%m%lx = lx
      fe_f%m%ly = ly
      fe_f%m%zx = 0.
      fe_f%m%zy = 0.
      call create_rect_FE_film( data_f = data_f,   &
                                 num_p = num_pts,  &
                                  fe_f = fe_f)
      write(OPU,*) 'film created'
   return
   endsubroutine init_fe_prob
Call graph
init_fe_prob calls create_rect_fe_film
create_rect_fe_film calls create_rect_x_ymesh
test_pocket_fe calls init_fe_prob
test_bearing_y_fe calls init_fe_prob
test_rough_fe calls init_fe_prob
test_bearing_x_fe calls init_fe_prob
test_slider_fe calls init_fe_prob
run_test calls test_pocket_fe, test_bearing_y_fe, test_rough_fe, test_bearing_x_fe, test_slider_fe
read_config calls run_test
main calls read_config