init_ms_prob – MUSST
init_ms_prob Subroutine
13 statements
Source File
private subroutine init_ms_prob()
Note
Subroutine to initialize a multiscale 'smooth' problem
Arguments
None
Calls
Called by
Contents
Source Code
init_ms_prob
Source Code
   subroutine init_ms_prob
   implicit none
      n_mic = (nx - 1) / n_mac +1
      ms_fe_f%ts_fe_f%m%nx = n_mac +1
      ms_fe_f%ts_fe_f%m%ny = n_mac +1
      ms_fe_f%ts_fe_f%m%lx = lx
      ms_fe_f%ts_fe_f%m%ly = ly
      ms_fe_f%ts_fe_f%m%zx = 0.
      ms_fe_f%ts_fe_f%m%zy = 0.
      call multi_scale_create_rect_fe_film(data_f = data_f,    &
                                            bs_nx = n_mic,     &
                                            bs_ny = n_mic,     &
                                          num_pts = num_pts,   &
                                          num_pbs = num_pbs,   &
                                          ms_fe_f = ms_fe_f)
      write(OPU,*) 'film created'
   return
   endsubroutine init_ms_prob
Call graph
init_ms_prob calls multi_scale_create_rect_fe_film
multi_scale_create_rect_fe_film calls create_rect_fe_film
create_rect_fe_film calls create_rect_x_ymesh
test_rough_ms calls init_ms_prob
test_slider_ms calls init_ms_prob
run_test calls test_rough_ms, test_slider_ms
read_config calls run_test
main calls read_config