modify_h_slider – MUSST
modify_h_slider Subroutine
11 statements
Source File
private subroutine modify_h_slider(fe_f, lx)
Note
Subroutine to define the slider geometry
Arguments
Type Intent Optional Attributes Name
type(FE_FILM), intent(inout) :: fe_f
real(kind=R8), intent(in) :: lx
Called by
Contents
Source Code
modify_h_slider
Source Code
   subroutine modify_h_slider(fe_f, lx)
   implicit none
   type(FE_FILM), intent(inout) :: fe_f
   real(kind=R8), intent(in)    :: lx
      integer(kind=I4) :: i
      do i = 1, fe_f%m%n
         fe_f%vn(i, H2_N) = fe_f%data_f%h_0 + fe_f%data_f%h_0 * (lx - fe_f%m%x(i)) / lx
      enddo
      fe_f%vn(:, H_N) = fe_f%vn(:, H2_N) - fe_f%vn(:, H1_N)
   return
   endsubroutine modify_h_slider
Call graph
modify_h_slider_ms calls modify_h_slider
test_slider_fe calls modify_h_slider
test_slider_ms calls modify_h_slider_ms
run_test calls test_slider_fe, test_slider_ms
read_config calls run_test
main calls read_config