prep_superlu – MUSST
prep_superlu Subroutine
25 statements
Source File
public subroutine prep_superlu(sulu)
Note
Subroutine to prepare the SULU_ENV components
Arguments
Type Intent Optional Attributes Name
type(SULU_ENV), intent(inout) :: sulu
Calls
Called by
Contents
Source Code
prep_superlu
Source Code
   subroutine prep_superlu(sulu)
   implicit none
   type(sulu_env), intent(inout) :: sulu
      integer(kind=I4) :: nn, nz, nb
      nn = sulu%n
      nz = sulu%nz
      nb = sulu%nrhs
      if (.not.allocated( sulu%perm_c )) then
         allocate( sulu%perm_c(1:nn) )
         allocate( sulu%perm_r(1:nn) )
         allocate( sulu%etree( 1:nn) )
         allocate( sulu%RR(1:nn) )
         allocate( sulu%CC(1:nn) )
         allocate( sulu%ferr(1:nb) )
         allocate( sulu%berr(1:nb) )
         allocate(   sulu%rpg(1:nb) )
         allocate( sulu%rcond(1:nb) )
         allocate( sulu%x(1:nn) )
      endif
      sulu%x(1:nn) = 0
      call dCreate_CompCol_Matrix(  A      = sulu%SMA,     & ! out SuperMatrix
                                    m      = sulu%n,       & ! in int
                                    n      = sulu%n,       & ! in int
                                    nnz    = sulu%nz,      & ! in int
                                    nzval  = sulu%a_elt,   & ! in double dimension()
                                    rowind = sulu%irow,    & ! in int dimension()
                                    colptr = sulu%jptr,    & ! in int dimension()
                                    stype  = SLU_NC,       & ! in int
                                    dtype  = SLU_D,        & ! in int
                                    mtype  = SLU_GE        & ! in int
                                 )
      call dCreate_Dense_Matrix( BX    = sulu%smb,  & ! out SuperMatrix
                                 m     = sulu%n,    & ! in int
                                 n     = sulu%nrhs, & ! in int
                                 x     = sulu%b,    & ! in double dimension()
                                 ldx   = sulu%n,    & ! in int
                                 stype = SLU_DN,    & ! in int
                                 dtype = SLU_D,     & ! in int
                                 mtype = SLU_GE     & ! in int
                               )
      call dCreate_Dense_Matrix( BX    = sulu%smx,  & ! out SuperMatrix
                                 m     = sulu%n,    & ! in int
                                 n     = sulu%nrhs, & ! in int
                                 x     = sulu%x,    & ! in double dimension()
                                 ldx   = sulu%n,    & ! in int
                                 stype = SLU_DN,    & ! in int
                                 dtype = SLU_D,     & ! in int
                                 mtype = SLU_GE     & ! in int
                               )
   return
   endsubroutine prep_superlu
Call graph
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
analyse_solver calls prep_superlu
solv_superlu calls prep_superlu
solution_solver calls solv_superlu
solve_syst calls analyse_solver, solution_solver
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_fe_prob calls solve_fe_film
test_rough_fe calls solve_fe_prob
test_bearing_x_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
run_test calls test_rough_fe, test_bearing_x_fe, test_pocket_fe, test_bearing_y_fe, test_rough_ms, test_slider_fe, test_slider_ms
main calls run_test