read_config – MUSST
read_config Subroutine
59 statements
Source File
subroutine read_config()
Arguments
None
Calls
Called by
Contents
Source Code
read_config
Source Code
   subroutine read_config()
   implicit none
      integer(kind=I4)   :: jf, err_read, test_num
      character(len=032) :: word
      character(len=128) :: job_copy
      job_copy = "out/"//repos//job_file(4:len_trim(job_file))
      call get_unit(jf) ; open(jf, file = trim(job_file), status = 'old')
         do
            word = repeat(' ', len(word))
            read(jf, *, iostat = err_read) word
            if ( index(word, 'END_FILE'      ) /= 0 ) then
               if (OPU/=OUT_U) close(OPU)
               exit
            endif
            if ( index(word, 'VERBOSE'       ) /= 0 ) then
               read(jf, *) VERBOSE
            endif
            if ( index(word, 'SOLV_MESS'     ) /= 0 ) then
               read(jf, *) SOLV_MESS
            endif
            if ( index(word, 'OUTPUT_UNIT'   ) /= 0 ) then
               read(jf, *) OPU
               if (OPU==0) then
                  OPU = OUT_U
               else
                  read(jf, *) OUTPUT_FILE
                  call get_unit(OPU)
                  open(unit = OPU,                          &
                       file = trim(adjustl(OUTPUT_FILE)),   &
                     status = 'unknown')
               endif
            endif
            if ( index(word, 'SOLVER_BS'     ) /= 0 ) then
               read(jf, *) SOLVER_BS
               if (SOLVER_BS==1) stop "some remaining problems with SuLU, choose '3' instead"
               if (SOLVER_BS==2) stop "MUMPS is multithreaded, it is designed for TS, choose '3' instead"
            endif
            if ( index(word, 'SOLVER_TS'     ) /= 0 ) then
               read(jf, *) SOLVER_TS
            endif
            if ( index(word, 'EXEC_MUSST'    ) /= 0 ) then
               read(jf, *) test_num
               call run_test(test_num, jf, repos)
            endif
            if ( index(word, 'NB_THREADS_MAX') /= 0 ) then
               read(jf, *) NB_THREADS_MAX
               if (NB_THREADS_MAX<0) then
                  !$ NB_THREADS_MAX = omp_get_num_procs()
               endif
            endif
            if ( index(word, 'ARCHIVE') /= 0 ) then
               read(jf, *) ARCHIVE
               if (ARCHIVE==1) then
                  call execute_command_line("sh bin/save/save.sh", wait=.true.)
                  call execute_command_line("mv *.7z out/"//repos//"/")
               endif
            endif
         enddo
      close(jf)
   return
   endsubroutine read_config
Call graph
read_config calls get_unit, run_test
run_test calls get_unit, test_slider_ms, read_data, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
test_slider_ms calls solve_ms_prob, init_ms_prob, modify_h_slider_ms
test_bearing_x_fe calls init_fe_prob, modify_h_bearing, solve_fe_prob
test_rough_ms calls apply_roughness_ms, solve_ms_prob, init_ms_prob, init_rough_prob
test_bearing_y_fe calls modify_h_bearing_y, init_fe_prob, solve_fe_prob
test_rough_fe calls apply_roughness, init_fe_prob, init_rough_prob, solve_fe_prob
test_pocket_fe calls modify_h_pocket, init_fe_prob, solve_fe_prob
test_slider_fe calls modify_h_slider, init_fe_prob, solve_fe_prob
apply_roughness_ms calls apply_roughness
solve_ms_prob calls save_ms_field, multi_scale_solve_fe_film
init_ms_prob calls multi_scale_create_rect_fe_film
init_fe_prob calls create_rect_fe_film
modify_h_slider_ms calls modify_h_slider
solve_fe_prob calls solve_fe_film, compute_corner_fluxes, save_fe_field
solve_fe_film calls apply_bc_fe_film_simple, assembly_fe_film_reynolds, omp_get_thread_num, solve_syst, apply_bc_fe_film, convert_matrice_format
create_rect_fe_film calls create_rect_x_ymesh
save_ms_field calls write_surf, ms_fe_f_2_mat, empty, init_scal
compute_corner_fluxes calls assembly_fe_film_reynolds
save_fe_field calls write_surf, empty, init_scal
multi_scale_solve_fe_film calls solve_fe_film, apply_bc_fe_film_simple, multi_scale_assembly_fe_film_reynolds, omp_get_thread_num, solve_syst, convert_matrice_format
multi_scale_create_rect_fe_film calls create_rect_fe_film
write_surf calls get_unit, lower, surf2scal, scal2surf
assembly_fe_film_reynolds calls elementary_assembly_fe_film_reynolds, assemble_in_mat_sol
multi_scale_assembly_fe_film_reynolds calls omp_get_thread_num
solve_syst calls factorize_solver, freefact_solver, init_solver, solution_solver, analyse_solver, close_solver
convert_matrice_format calls from_elemental_to_assembled
init_scal calls empty
factorize_solver calls s_umfpack_di_numeric, ma48_factorize, umfpack_di_free_numeric, dmumps
freefact_solver calls free_superlu, umfpack_di_free_numeric
init_solver calls mpi_init, umfpack_di_defaults, ma48_initialize, init_superlu, mpi_finalize, umfpack_di_report_control, dmumps
surf2scal calls c_f_string
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
solution_solver calls solv_superlu, s_umfpack_di_solve, ma48_solve, mpi_finalize, dmumps
analyse_solver calls ma48_analyse, prep_superlu, s_umfpack_di_symbolic, dmumps
close_solver calls umfpack_di_report_info, ma48_finalize, umfpack_di_free_numeric, mpi_finalize, umfpack_di_free_symbolic, dmumps, close_superlu
solv_superlu calls prep_superlu, statfree, statinit, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_di_solve calls umfpack_di_solve
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
compute_prc_tables_reynolds_supg calls ni4_up_2d, length_width_elem, dj4
init_superlu calls set_default_options
c_f_string calls empty
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
umfpack_di_numeric calls c_umfpack_di_numeric
ni4_up_2d calls ni4_up_1d
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
main calls read_config