run_test – MUSST
run_test Subroutine
30 statements
Source File
public subroutine run_test(test, iunit, dir)
Note
Subroutine to read the data file .dat in the 'EXEC_MUSST' section and then to run the specified test
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(in) :: test
number of the test to be performed
integer(kind=I4), intent(in) :: iunit
unit number of the data file
character(len=15), intent(in) :: dir
output directory
Calls
Called by
Contents
Source Code
run_test
Source Code
   subroutine run_test(test, iunit, dir)
   implicit none
   integer(kind=I4),  intent(in) :: test   !! *number of the test to be performed*
   integer(kind=I4),  intent(in) :: iunit  !! *unit number of the data file*
   character(len=15), intent(in) :: dir    !! *output directory*
      test_num = test
      call read_data(iunit, dir)
      ! when ```run_test``` has been launched, *SOLVER_TS* has been determined
      mat%slv_t = SOLVER_TS
      call get_unit(unit_num_res) ; open(unit = unit_num_res, file = trim(res_file), status = 'unknown')
      select case(test)
         case( 1); call test_slider_fe
         case(11); call test_slider_ms
         case( 2); call test_bearing_x_fe
         case( 3); call test_bearing_y_fe
         case( 4); call test_rough_fe
         case(14); call test_rough_ms
         case( 5); call test_pocket_fe
         case default
      endselect
      close(unit_num_res)
   return
   endsubroutine run_test
Call graph
run_test calls test_slider_ms, read_data, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, get_unit, test_slider_fe
test_slider_ms calls solve_ms_prob, init_ms_prob, modify_h_slider_ms
test_bearing_x_fe calls init_fe_prob, modify_h_bearing, solve_fe_prob
test_rough_ms calls apply_roughness_ms, solve_ms_prob, init_ms_prob, init_rough_prob
test_bearing_y_fe calls modify_h_bearing_y, init_fe_prob, solve_fe_prob
test_rough_fe calls apply_roughness, init_fe_prob, init_rough_prob, solve_fe_prob
test_pocket_fe calls modify_h_pocket, init_fe_prob, solve_fe_prob
test_slider_fe calls modify_h_slider, init_fe_prob, solve_fe_prob
apply_roughness_ms calls apply_roughness
solve_ms_prob calls save_ms_field, multi_scale_solve_fe_film
init_ms_prob calls multi_scale_create_rect_fe_film
init_fe_prob calls create_rect_fe_film
modify_h_slider_ms calls modify_h_slider
solve_fe_prob calls solve_fe_film, compute_corner_fluxes, save_fe_field
solve_fe_film calls apply_bc_fe_film_simple, assembly_fe_film_reynolds, omp_get_thread_num, solve_syst, apply_bc_fe_film, convert_matrice_format
create_rect_fe_film calls create_rect_x_ymesh
save_ms_field calls write_surf, ms_fe_f_2_mat, empty, init_scal
compute_corner_fluxes calls assembly_fe_film_reynolds
save_fe_field calls write_surf, empty, init_scal
multi_scale_solve_fe_film calls solve_fe_film, apply_bc_fe_film_simple, multi_scale_assembly_fe_film_reynolds, omp_get_thread_num, solve_syst, convert_matrice_format
multi_scale_create_rect_fe_film calls create_rect_fe_film
write_surf calls get_unit, lower, surf2scal, scal2surf
assembly_fe_film_reynolds calls elementary_assembly_fe_film_reynolds, assemble_in_mat_sol
multi_scale_assembly_fe_film_reynolds calls omp_get_thread_num
solve_syst calls factorize_solver, freefact_solver, init_solver, solution_solver, analyse_solver, close_solver
convert_matrice_format calls from_elemental_to_assembled
init_scal calls empty
factorize_solver calls s_umfpack_di_numeric, ma48_factorize, umfpack_di_free_numeric, dmumps
freefact_solver calls free_superlu, umfpack_di_free_numeric
init_solver calls mpi_init, umfpack_di_defaults, ma48_initialize, init_superlu, mpi_finalize, umfpack_di_report_control, dmumps
surf2scal calls c_f_string
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
solution_solver calls solv_superlu, s_umfpack_di_solve, ma48_solve, mpi_finalize, dmumps
analyse_solver calls ma48_analyse, prep_superlu, s_umfpack_di_symbolic, dmumps
close_solver calls umfpack_di_report_info, ma48_finalize, umfpack_di_free_numeric, mpi_finalize, umfpack_di_free_symbolic, dmumps, close_superlu
solv_superlu calls prep_superlu, statfree, statinit, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_di_solve calls umfpack_di_solve
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
compute_prc_tables_reynolds_supg calls ni4_up_2d, length_width_elem, dj4
init_superlu calls set_default_options
c_f_string calls empty
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
umfpack_di_numeric calls c_umfpack_di_numeric
ni4_up_2d calls ni4_up_1d
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
read_config calls run_test
main calls read_config