s_umfpack_di_numeric – MUSST
s_umfpack_di_numeric Subroutine
11 statements
Source File
public subroutine s_umfpack_di_numeric(Ap, Ai, Ax, Symbolic, Numeric, Control, Info, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Ap(*)
integer, intent(in) :: Ai(*)
real(kind=r8), intent(in) :: Ax(*)
type(c_ptr), intent(in), optional :: Symbolic
type(c_ptr), optional :: Numeric
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional :: Info(0:UMFPACK_INFO-1)
integer, optional :: status
Calls
Called by
Contents
None
Call graph
s_umfpack_di_numeric calls umfpack_di_numeric
umfpack_di_numeric calls c_umfpack_di_numeric
factorize_solver calls s_umfpack_di_numeric
s_umfpack_numeric calls s_umfpack_di_numeric
umfpack_di_operator_csr calls s_umfpack_di_numeric
umfpack_di_operator_pcsc calls s_umfpack_di_numeric
umfpack_di_operator_csc calls s_umfpack_di_numeric
umfpack_di_operator_pcsr calls s_umfpack_di_numeric
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_csc, umfpack_di_operator_pcsr
umf4znum calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4znum
umf4cnum_ip calls s_umfpack_numeric
umf4num calls s_umfpack_numeric, umf4cnum_ip, umf4znum_ip, umf4num_ip, umf4num
solve_syst calls factorize_solver
umf4znum_ip calls s_umfpack_numeric
umf4cnum calls s_umfpack_numeric, umf4cnum_ip, umf4cnum
umf4num_ip calls s_umfpack_numeric
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config