scal2surf – MUSST
scal2surf Subroutine
60 statements
Source File
public subroutine scal2surf(scal, surf)
Arguments
Type Intent Optional Attributes Name
type(SCALE_SURF), intent(in) :: scal
object SCALE_SURF
type(OBJ_SURF), intent(out) :: surf
object OBJ_SURF
Called by
Contents
Source Code
scal2surf
Source Code
   subroutine scal2surf(scal, surf)
   implicit none
   type(SCALE_SURF), intent(in ) :: scal !! *object [[SCALE_SURF]]*
   type(OBJ_SURF),   intent(out) :: surf !! *object [[OBJ_SURF]]*
      call f_c_string(fs=trim(scal%signature),     &
                      cs=     surf%signature)
      call f_c_string(fs=trim(scal%xlength_unit),  &
                      cs=     surf%xlength_unit)
      call f_c_string(fs=trim(scal%ylength_unit),  &
                      cs=     surf%ylength_unit)
      call f_c_string(fs=trim(scal%zlength_unit),  &
                      cs=     surf%zlength_unit)
      call f_c_string(fs=trim(scal%xaxis),         &
                      cs=     surf%xaxis)
      call f_c_string(fs=trim(scal%yaxis),         &
                      cs=     surf%yaxis)
      call f_c_string(fs=trim(scal%zaxis),         &
                      cs=     surf%zaxis)
      call f_c_string(fs=trim(scal%dx_unit),       &
                      cs=     surf%dx_unit)
      call f_c_string(fs=trim(scal%dy_unit),       &
                      cs=     surf%dy_unit)
      call f_c_string(fs=trim(scal%dz_unit),       &
                      cs=     surf%dz_unit)
      call f_c_string(fs=trim(scal%object_name),   &
                      cs=     surf%object_name)
      call f_c_string(fs=trim(scal%operator_name), &
                      cs=     surf%operator_name)
      call f_c_string(fs=trim(scal%client_zone),   &
                      cs=     surf%client_zone)
      call f_c_string(fs=trim(scal%reserved),      &
                      cs=     surf%reserved)
      call f_c_string(fs=trim(scal%reservedzone),  &
                      cs=     surf%reservedzone)
      call f_c_string(fs=trim(scal%obsolete),      &
                      cs=     surf%obsolete)
      call f_c_string(fs=trim(scal%obsolete2),     &
                      cs=     surf%obsolete2)
      surf%dx                    = scal%dx
      surf%dy                    = scal%dy
      surf%dz                    = scal%dz
      surf%xunit_ratio           = scal%xunit_ratio
      surf%yunit_ratio           = scal%yunit_ratio
      surf%zunit_ratio           = scal%zunit_ratio
      surf%XOffset               = scal%XOffset
      surf%YOffset               = scal%YOffset
      surf%ZOffset               = scal%ZOffset
      surf%measurement_duration  = scal%measurement_duration
      surf%zmin      = scal%zmin
      surf%zmax      = scal%zmax
      surf%xres      = scal%xres
      surf%yres      = scal%yres
      surf%nofpoints = scal%nofpoints
      surf%format          = scal%format
      surf%version         = scal%version
      surf%material_code   = scal%material_code
      surf%type            = scal%type
      surf%range           = scal%range
      surf%special_points  = scal%special_points
      surf%absolute        = scal%absolute
      surf%pointsize       = scal%pointsize
      surf%imprint         = scal%imprint
      surf%inversion       = scal%inversion
      surf%leveling        = scal%leveling
      surf%seconds         = scal%seconds
      surf%minutes         = scal%minutes
      surf%hours           = scal%hours
      surf%day             = scal%day
      surf%month           = scal%month
      surf%year            = scal%year
      surf%dayof           = scal%dayof
      surf%comment_size    = scal%comment_size
      surf%private_size    = scal%private_size
      surf%nobjects        = scal%nobjects
      surf%acquisition     = scal%acquisition
   return
   endsubroutine scal2surf
Call graph
write_surf calls scal2surf
save_ms_field calls write_surf
save_fe_field calls write_surf
solve_ms_prob calls save_ms_field
solve_fe_prob calls save_fe_field
test_rough_fe calls solve_fe_prob
test_bearing_x_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
run_test calls test_rough_fe, test_bearing_x_fe, test_pocket_fe, test_bearing_y_fe, test_rough_ms, test_slider_fe, test_slider_ms
main calls run_test