solve_fe_prob – MUSST
solve_fe_prob Subroutine
38 statements
Source File
private subroutine solve_fe_prob()
Note
Subroutine to solve a deterministic 'smooth' problem
Arguments
None
Calls
Called by
Contents
Source Code
solve_fe_prob
Source Code
   subroutine solve_fe_prob
   implicit none
      call system_clock(count=cinit)
      call cpu_time(t1)
         call solve_FE_film(fe_f, mat, bc)
         call compute_corner_fluxes(fe_f, mat, bf)
      call cpu_time(t2)
      call system_clock(count=cend,count_rate=cr)
      write(OPU,*)          'FE cpu time (s):',          char(9), t2 - t1
      write(unit_num_res,*) 'FE_cpu_time_(s):',          char(9), t2 - t1
      write(OPU,*)          'FE real comp time (s):',    char(9), real(cend - cinit) / real(cr)
      write(unit_num_res,*) 'FE_real_comp_time_(s):',    char(9), real(cend - cinit) / real(cr)
      save_PeK = .false.
      save_PeE = .false.
      if (s_vtk /= NO_VTK) call save_fe_f_vtk(fe_f, trim(ms_vtk))
      select case(test_num)
         case (1)
            call save_profile_x_comp_slider(fe_f, trim(prof_ts), lx, ly / 2)
            call execute_command_line("python3 bin/pyt/filetoplot.py "// trim(prof_ts) //" '$x/L$' '$ph^2/6 \mu V L$' ")
         case (5)
            call save_profile_y_comp_air_pocket(fe_f, trim(prof_ts), ly, lx/2, bc)
            call execute_command_line("python3 bin/pyt/filetoplot.py "// trim(prof_ts) //" '$x/L$' '$ph^2/6 \mu V L$' ")
            call save_profile_x_comp_air_pocket(fe_f, trim(prof_ts)//'2', lx, ly / 2, bc)
            call execute_command_line("python3 bin/pyt/filetoplot.py "// trim(prof_ts)//'2' //" '$x/L$' '$ph^2/6 \mu V L$' ")
         case default
            call save_profile_x_fe(fe_f, trim(prof_ts), lx, ly / 2)
      endselect
      call save_fe_field(fe_f = fe_f,                                   & !
                    file_name = "out/"//res_dir//"/"//"pressure.sur",   & !
                         code = P_N,                                    & !
                        nodal = .true.)
      if (save_PeK) & !
      call save_fe_field(fe_f = fe_f,                                   & !
                    file_name = "out/"//res_dir//"/"//"PeK.sur",        & !
                         code = PEK_C,                                  & !
                        nodal = .false.)
      if (save_PeE) & !
      call save_fe_field(fe_f = fe_f,                                   & !
                    file_name = "out/"//res_dir//"/"//"PeE.sur",        & !
                         code = PEE_C,                                  & !
                        nodal = .false.)
      write(OPU,*)          'load FE (N):',  char(9), fe_f%fz()
      write(unit_num_res,*) 'load_FE_(N):',  char(9), fe_f%fz()
      write(OPU,*)          'fric/x FE (N)', char(9), fe_f%fx()
      write(unit_num_res,*) 'fric/x_FE_(N)', char(9), fe_f%fx()
      write(OPU,*)          'fric/y FE (N)', char(9), fe_f%fy()
      write(unit_num_res,*) 'fric/y_FE_(N)', char(9), fe_f%fy()
   return
   endsubroutine solve_fe_prob
Call graph
solve_fe_prob calls solve_fe_film, compute_corner_fluxes, save_fe_field
solve_fe_film calls apply_bc_fe_film_simple, assembly_fe_film_reynolds, omp_get_thread_num, solve_syst, apply_bc_fe_film, convert_matrice_format
compute_corner_fluxes calls assembly_fe_film_reynolds
save_fe_field calls write_surf, empty, init_scal
write_surf calls lower, surf2scal, get_unit, scal2surf
assembly_fe_film_reynolds calls elementary_assembly_fe_film_reynolds, assemble_in_mat_sol
solve_syst calls factorize_solver, freefact_solver, init_solver, solution_solver, analyse_solver, close_solver
convert_matrice_format calls from_elemental_to_assembled
init_scal calls empty
factorize_solver calls s_umfpack_di_numeric, ma48_factorize, umfpack_di_free_numeric, dmumps
freefact_solver calls free_superlu, umfpack_di_free_numeric
init_solver calls mpi_init, umfpack_di_defaults, ma48_initialize, init_superlu, mpi_finalize, umfpack_di_report_control, dmumps
surf2scal calls c_f_string
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
solution_solver calls solv_superlu, s_umfpack_di_solve, ma48_solve, mpi_finalize, dmumps
analyse_solver calls ma48_analyse, prep_superlu, s_umfpack_di_symbolic, dmumps
close_solver calls umfpack_di_report_info, ma48_finalize, umfpack_di_free_numeric, mpi_finalize, umfpack_di_free_symbolic, dmumps, close_superlu
solv_superlu calls prep_superlu, statfree, statinit, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_di_solve calls umfpack_di_solve
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
compute_prc_tables_reynolds_supg calls ni4_up_2d, length_width_elem, dj4
init_superlu calls set_default_options
c_f_string calls empty
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
umfpack_di_numeric calls c_umfpack_di_numeric
ni4_up_2d calls ni4_up_1d
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
test_pocket_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_bearing_x_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_pocket_fe, test_bearing_y_fe, test_rough_fe, test_bearing_x_fe, test_slider_fe
read_config calls run_test
main calls read_config