solve_ms_prob – MUSST
solve_ms_prob Subroutine
50 statements
Source File
private subroutine solve_ms_prob()
Note
Subroutine to solve a 'smooth' multiscale problem
Arguments
None
Calls
Called by
Contents
Source Code
solve_ms_prob
Source Code
   subroutine solve_ms_prob
   implicit none
      real(kind=R8), dimension(:, :), allocatable :: tab
      call system_clock(count=cinit)
      call cpu_time(t1)
         call multi_scale_solve_fe_film(ms_fe_f, ms_mat, bc)
      call cpu_time(t2)
      call system_clock(count=cend,count_rate=cr)
      write(OPU,*)          'MS cpu time (s):',          char(9), t2 - t1
      write(unit_num_res,*) 'MS_cpu_time_(s):',          char(9), t2 - t1
      write(OPU,*)          'MS real comp time (s):',    char(9), real(cend - cinit) / real(cr)
      write(unit_num_res,*) 'MS_real_comp_time_(s):',    char(9), real(cend - cinit) / real(cr)
      write(OPU,*)          'load MS_FE (N):',           char(9), ms_fe_f%ms_fz()
      write(unit_num_res,*) 'load_MS_FE_(N):',           char(9), ms_fe_f%ms_fz()
      write(OPU,*)          'fric/x MS FE (N):',         char(9), ms_fe_f%ms_fx()
      write(unit_num_res,*) 'fric/x_MS_FE_(N):',         char(9), ms_fe_f%ms_fx()
      write(OPU,*)          'fric/y MS FE (N):',         char(9), ms_fe_f%ms_fy()
      write(unit_num_res,*) 'fric/y_MS_FE_(N):',         char(9), ms_fe_f%ms_fy()
      call save_ms_fe_f_vtk(ms_fe_f, trim(ms_vtk))
      call save_profile_x_fe(ms_fe_f%ts_fe_f, trim(prof_ts), lx, ly/2)
      call save_profile_x_ms(ms_fe_f,         trim(prof_bs), lx, ly/2)
      call save_ms_field(ms_fe_f = ms_fe_f,                                   & !
                       file_name = "out/"//res_dir//"/"//"ms_pressure.sur",   & !
                            code = P_N,                                       & !
                           nodal = .true.                                     )
      if (compare_solution_file /= 0) then
         if ( allocated(tab_sol) ) deallocate(tab_sol)
         call read_surf(nom_fic = trim(pressure_solution_file),   & !
                             mu = -1._R8,                         & !
                             sq = -1._R8,                         & !
                          tab_s = tab_sol,                        & !
                           scal = scal_tmp)
         if ( allocated(tab_s) ) deallocate(tab_s)
         call ms_fe_f_2_mat(ms_fe_f = ms_fe_f,  & !
                               code = P_N,      & !
                              nodal = .true.,   & !
                                mat = tab_s)
         allocate( tab(1:nx, 1:ny) )
         tab(1:nx, 1:ny) = abs(tab_s(1:nx, 1:ny) -tab_sol(1:nx, 1:ny))
         scal_tmp%zlength_unit = 'Pa'
         scal_tmp%dz_unit      = 'Pa'
         call write_surf(nom_fic = "out/"//res_dir//"/"//"compare_pressure.sur",    & !
                           tab_s = tab(1:nx, 1:ny),                                 & !
                            scal = scal_tmp)
         where (tab_s < data_f%fl%p_0 .and. tab_sol > data_f%fl%p_0)
            tab = -1._R8
         elsewhere (tab_s > data_f%fl%p_0 .and. tab_sol < data_f%fl%p_0)
            tab = +1._R8
         elsewhere (tab_s < data_f%fl%p_0 .and. tab_sol < data_f%fl%p_0)
            tab =  0._R8
         elsewhere
            tab = -2._R8
         endwhere
         scal_tmp%zlength_unit = '  '
         scal_tmp%dz_unit      = '  '
         call write_surf(nom_fic = "out/"//res_dir//"/"//"compare_cavitation.sur",  & !
                           tab_s = tab(1:nx, 1:ny),                                 & !
                            scal = scal_tmp)
      endif
      if ( allocated(tab    ) ) deallocate(tab    )
      if ( allocated(tab_s  ) ) deallocate(tab_s  )
      if ( allocated(tab_sol) ) deallocate(tab_sol)
   return
   endsubroutine solve_ms_prob
Call graph
solve_ms_prob calls multi_scale_solve_fe_film, save_ms_field, ms_fe_f_2_mat
multi_scale_solve_fe_film calls solve_syst, convert_matrice_format, multi_scale_assembly_fe_film_reynolds, omp_get_thread_num, apply_bc_fe_film_simple, solve_fe_film
save_ms_field calls ms_fe_f_2_mat, init_scal, write_surf, empty
solve_syst calls close_solver, init_solver, solution_solver, analyse_solver, factorize_solver, freefact_solver
convert_matrice_format calls from_elemental_to_assembled
multi_scale_assembly_fe_film_reynolds calls omp_get_thread_num
init_scal calls empty
write_surf calls scal2surf, lower, get_unit, surf2scal
solve_fe_film calls solve_syst, convert_matrice_format, omp_get_thread_num, apply_bc_fe_film_simple, assembly_fe_film_reynolds, apply_bc_fe_film
close_solver calls umfpack_di_free_symbolic, umfpack_di_report_info, close_superlu, dmumps, mpi_finalize, umfpack_di_free_numeric, ma48_finalize
init_solver calls umfpack_di_defaults, dmumps, mpi_finalize, init_superlu, ma48_initialize, umfpack_di_report_control, mpi_init
assembly_fe_film_reynolds calls elementary_assembly_fe_film_reynolds, assemble_in_mat_sol
solution_solver calls s_umfpack_di_solve, solv_superlu, dmumps, mpi_finalize, ma48_solve
surf2scal calls c_f_string
analyse_solver calls ma48_analyse, dmumps, prep_superlu, s_umfpack_di_symbolic
factorize_solver calls dmumps, umfpack_di_free_numeric, s_umfpack_di_numeric, ma48_factorize
freefact_solver calls umfpack_di_free_numeric, free_superlu
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
s_umfpack_di_solve calls umfpack_di_solve
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
close_superlu calls destroy_dense_matrix, destroy_compcol_matrix
solv_superlu calls prep_superlu, statinit, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix, statfree
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
init_superlu calls set_default_options
prep_superlu calls dcreate_compcol_matrix, dcreate_dense_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
c_f_string calls empty
umfpack_di_report_control calls c_umfpack_di_report_control
compute_prc_tables_reynolds_supg calls ni4_up_2d, dj4, length_width_elem
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
ni4_up_2d calls ni4_up_1d
test_rough_ms calls solve_ms_prob
test_slider_ms calls solve_ms_prob
run_test calls test_rough_ms, test_slider_ms
main calls run_test