solve_syst – MUSST
solve_syst Subroutine
31 statements
Source File
public subroutine solve_syst(mat, step)
Note
General hat subroutine that handles the resolution steps:
* ini solver initialization
* ana solver analyzis when it's proposed by the solver
* fac solver factorization
* sol solver solution
* fre solver memory release when it's proposed by the solver
* end solver end
Arguments
Type Intent Optional Attributes Name
type(MAT_SOLV), intent(inout) :: mat
high level system type
character(len=*), intent(in) :: step
'ini'=initialize, 'ana'=analyze, 'fac'=factorize, 'sol'=solve, 'fre'=free memory, 'end'=close solver
Calls
Called by
Contents
Source Code
solve_syst
Source Code
   subroutine solve_syst(mat, step)
   implicit none
   type(MAT_SOLV), intent(inout) :: mat   !! *high level system type*
   character(len=*), intent(in)  :: step  !! *'ini'=initialize, 'ana'=analyze, 'fac'=factorize, 'sol'=solve, 'fre'=free memory, 'end'=close solver*
      if ( index(step, 'ini')/=0 ) then ; call init_solver(     mat) ; return ; endif
      if ( index(step, 'ana')/=0 ) then ; call analyse_solver(  mat) ; return ; endif
      if ( index(step, 'fac')/=0 ) then ; call factorize_solver(mat) ; return ; endif
      if ( index(step, 'sol')/=0 ) then ; call solution_solver( mat) ; return ; endif
      if ( index(step, 'fre')/=0 ) then ; call freefact_solver( mat) ; return ; endif
      if ( index(step, 'end')/=0 ) then ; call close_solver( mat)    ; return ; endif
      stop 'Bad step chosen in SOLVE_SYST'
   return
   endsubroutine solve_syst
Call graph
solve_syst calls factorize_solver, freefact_solver, init_solver, solution_solver, analyse_solver, close_solver
factorize_solver calls umfpack_di_free_numeric, s_umfpack_di_numeric, ma48_factorize, dmumps
freefact_solver calls umfpack_di_free_numeric, free_superlu
init_solver calls ma48_initialize, mpi_finalize, umfpack_di_report_control, mpi_init, dmumps, init_superlu, umfpack_di_defaults
solution_solver calls mpi_finalize, solv_superlu, s_umfpack_di_solve, dmumps, ma48_solve
analyse_solver calls ma48_analyse, prep_superlu, s_umfpack_di_symbolic, dmumps
close_solver calls umfpack_di_free_numeric, mpi_finalize, umfpack_di_free_symbolic, ma48_finalize, umfpack_di_report_info, close_superlu, dmumps
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
s_umfpack_di_numeric calls umfpack_di_numeric
solv_superlu calls prep_superlu, statfree, statinit, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
s_umfpack_di_solve calls umfpack_di_solve
umfpack_di_report_info calls c_umfpack_di_report_info
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
init_superlu calls set_default_options
umfpack_di_defaults calls c_umfpack_di_defaults
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config