str_I8P – MUSST
str_I8P Function
11 statements
Source File
private elemental function str_I8P(no_sign, n) result(str)
The function str_I8P converts integer to string. This function achieves casting of integer to string.
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: no_sign
integer(kind=I8P), intent(in) :: n
Return Value character(len=DI8P)
Called by
Contents
Source Code
str_I8P
Source Code
  elemental function str_I8P(no_sign,n) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !!The function str\_I8P converts integer to string. This function achieves casting of integer to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  implicit none
  logical,      intent(IN), optional:: no_sign ! Flag for leaving out the sign.
  integer(I8P), intent(IN)::           n       ! Integer to be converted.
  character(DI8P)::                    str     ! Returned string containing input number plus padding zeros.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str,FI8P) n                 ! Casting of n to string.
  str = adjustl(trim(str))          ! Removing white spaces.
  if (n>=0_I8P) str='+'//trim(str)  ! Prefixing plus if n>0.
  if (present(no_sign)) str=str(2:) ! Leaving out the sign.
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_I8P
Call graph
str calls str_i8p
vtk_var_xml_list_i2 calls str
vtk_var_xml_scal_i4 calls str
vtk_geo_xml_strg_r4 calls str
vtk_var_xml_vect_i2 calls str
vtk_var_xml_list_r4 calls str
vtk_var_xml_vect_r4 calls str
vtk_var_xml_list_i4 calls str
vtk_var_xml_vect_i4 calls str
vtk_var_xml_scal_i8 calls str
vtk_geo_xml_strg_r8 calls str
vtk_var_xml_vect_i8 calls str
vtk_geo_xml_rect_r4 calls str
vtk_var_xml_vect_i1 calls str
vtk_var_xml_scal_i1 calls str
vtk_var_xml_list_i8 calls str
vtk_var_xml_vect_r8 calls str
vtk_var_xml_scal_r4 calls str
vtk_geo_xml_unst_r4 calls str
vtk_con_xml calls str
vtk_var_xml_list_i1 calls str
vtk_geo_xml_rect_r8 calls str
vtk_var_xml_scal_i2 calls str
vtk_var_xml_list_r8 calls str
vtk_var_xml_scal_r8 calls str
vtk_geo_xml_unst_r8 calls str
vtk_var_xml calls vtk_var_xml_list_i2, vtk_var_xml_scal_i4, vtk_var_xml_vect_i2, vtk_var_xml_list_r4, vtk_var_xml_vect_r4, vtk_var_xml_list_i4, vtk_var_xml_vect_i4, vtk_var_xml_scal_i8, vtk_var_xml_vect_i8, vtk_var_xml_vect_i1, vtk_var_xml_scal_i1, vtk_var_xml_list_i8, vtk_var_xml_vect_r8, vtk_var_xml_scal_r4, vtk_var_xml_list_i1, vtk_var_xml_scal_i2, vtk_var_xml_list_r8, vtk_var_xml_scal_r8
vtk_geo_xml calls vtk_geo_xml_strg_r4, vtk_geo_xml_strg_r8, vtk_geo_xml_rect_r4, vtk_geo_xml_unst_r4, vtk_geo_xml_rect_r8, vtk_geo_xml_unst_r8