str_R4P – MUSST
str_R4P Function
10 statements
Source File
private elemental function str_R4P(no_sign, n) result(str)
The function str_R4P converts real to string. This function achieves casting of real to string.
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: no_sign
real(kind=R4P), intent(in) :: n
Return Value character(len=DR4P)
Called by
Contents
Source Code
str_R4P
Source Code
  elemental function str_R4P(no_sign,n) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !!The function str\_R4P converts real to string. This function achieves casting of real to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  implicit none
  logical,   intent(IN), optional:: no_sign ! Flag for leaving out the sign.
  real(R4P), intent(IN)::           n       ! Real to be converted.
  character(DR4P)::                 str     ! Returned string containing input number.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str,FR4P) n                 ! Casting of n to string.
  if (n>0._R4P) str(1:1)='+'        ! Prefixing plus if n>0.
  if (present(no_sign)) str=str(2:) ! Leaving out the sign.
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_R4P
Call graph
str calls str_r4p
vtk_var_xml_list_r8 calls str
vtk_var_xml_list_i1 calls str
vtk_var_xml_scal_i2 calls str
vtk_var_xml_list_i4 calls str
vtk_var_xml_vect_r4 calls str
vtk_geo_xml_rect_r4 calls str
vtk_var_xml_vect_i8 calls str
vtk_var_xml_vect_i2 calls str
vtk_var_xml_vect_i1 calls str
vtk_geo_xml_rect_r8 calls str
vtk_var_xml_vect_r8 calls str
vtk_var_xml_scal_i1 calls str
vtk_var_xml_list_r4 calls str
vtk_geo_xml_unst_r4 calls str
vtk_var_xml_list_i2 calls str
vtk_geo_xml_strg_r8 calls str
vtk_var_xml_scal_i8 calls str
vtk_var_xml_scal_r8 calls str
vtk_var_xml_list_i8 calls str
vtk_geo_xml_unst_r8 calls str
vtk_geo_xml_strg_r4 calls str
vtk_var_xml_scal_i4 calls str
vtk_var_xml_scal_r4 calls str
vtk_var_xml_vect_i4 calls str
vtk_con_xml calls str
vtk_var_xml calls vtk_var_xml_list_r8, vtk_var_xml_list_i1, vtk_var_xml_scal_i2, vtk_var_xml_list_i4, vtk_var_xml_vect_r4, vtk_var_xml_vect_i8, vtk_var_xml_vect_i2, vtk_var_xml_vect_i1, vtk_var_xml_vect_r8, vtk_var_xml_scal_i1, vtk_var_xml_list_r4, vtk_var_xml_list_i2, vtk_var_xml_scal_i8, vtk_var_xml_scal_r8, vtk_var_xml_list_i8, vtk_var_xml_scal_i4, vtk_var_xml_scal_r4, vtk_var_xml_vect_i4
vtk_geo_xml calls vtk_geo_xml_rect_r4, vtk_geo_xml_rect_r8, vtk_geo_xml_unst_r4, vtk_geo_xml_strg_r8, vtk_geo_xml_unst_r8, vtk_geo_xml_strg_r4