surf2scal – MUSST
surf2scal Subroutine
61 statements
Source File
public subroutine surf2scal(surf, scal)
Arguments
Type Intent Optional Attributes Name
type(OBJ_SURF), intent(in) :: surf
object OBJ_SURF
type(SCALE_SURF), intent(out) :: scal
object SCALE_SURF
Calls
Called by
Contents
Source Code
surf2scal
Source Code
   subroutine surf2scal(surf, scal)
   implicit none
   type(OBJ_SURF),   intent(in ) :: surf !! *object [[OBJ_SURF]]*
   type(SCALE_SURF), intent(out) :: scal !! *object [[SCALE_SURF]]*
      integer(kind=I4) :: i
      call c_f_string(cs = surf%signature,     &
                      fs = scal%signature,     &
                 borne_s = i)
      call c_f_string(cs = surf%xlength_unit,  &
                      fs = scal%xlength_unit,  &
                 borne_s = i)
      call c_f_string(cs = surf%ylength_unit,  &
                      fs = scal%ylength_unit,  &
                 borne_s = i)
      call c_f_string(cs = surf%zlength_unit,  &
                      fs = scal%zlength_unit,  &
                 borne_s = i)
      call c_f_string(cs = surf%xaxis,         &
                      fs = scal%xaxis,         &
                 borne_s = i)
      call c_f_string(cs = surf%yaxis,         &
                      fs = scal%yaxis,         &
                 borne_s = i)
      call c_f_string(cs = surf%zaxis,         &
                      fs = scal%zaxis,         &
                 borne_s = i)
      call c_f_string(cs = surf%dx_unit,       &
                      fs = scal%dx_unit,       &
                 borne_s = i)
      call c_f_string(cs = surf%dy_unit,       &
                      fs = scal%dy_unit,       &
                 borne_s = i)
      call c_f_string(cs = surf%dz_unit,       &
                      fs = scal%dz_unit,       &
                 borne_s = i)
      call c_f_string(cs = surf%object_name,   &
                      fs = scal%object_name,   &
                 borne_s = i)
      call c_f_string(cs = surf%operator_name, &
                      fs = scal%operator_name, &
                 borne_s = i)
      call c_f_string(cs = surf%client_zone,   &
                      fs = scal%client_zone,   &
                 borne_s = i)
      call c_f_string(cs = surf%reserved,      &
                      fs = scal%reserved,      &
                 borne_s = i)
      call c_f_string(cs = surf%reservedzone,  &
                      fs = scal%reservedzone,  &
                 borne_s = i)
      call c_f_string(cs = surf%obsolete,      &
                      fs = scal%obsolete,      &
                 borne_s = i)
      call c_f_string(cs = surf%obsolete2,     &
                      fs = scal%obsolete2,     &
                 borne_s =i)
      scal%dx                    = surf%dx
      scal%dy                    = surf%dy
      scal%dz                    = surf%dz
      scal%xunit_ratio           = surf%xunit_ratio
      scal%yunit_ratio           = surf%yunit_ratio
      scal%zunit_ratio           = surf%zunit_ratio
      scal%XOffset               = surf%XOffset
      scal%YOffset               = surf%YOffset
      scal%ZOffset               = surf%ZOffset
      scal%measurement_duration  = surf%measurement_duration
      scal%zmin      = surf%zmin
      scal%zmax      = surf%zmax
      scal%xres      = surf%xres
      scal%yres      = surf%yres
      scal%nofpoints = surf%nofpoints
      scal%format          = surf%format
      scal%version         = surf%version
      scal%material_code   = surf%material_code
      scal%type            = surf%type
      scal%range           = surf%range
      scal%special_points  = surf%special_points
      scal%absolute        = surf%absolute
      scal%pointsize       = surf%pointsize
      scal%imprint         = surf%imprint
      scal%inversion       = surf%inversion
      scal%leveling        = surf%leveling
      scal%seconds         = surf%seconds
      scal%minutes         = surf%minutes
      scal%hours           = surf%hours
      scal%day             = surf%day
      scal%month           = surf%month
      scal%year            = surf%year
      scal%dayof           = surf%dayof
      scal%comment_size    = surf%comment_size
      scal%private_size    = surf%private_size
      scal%nobjects        = surf%nobjects
      scal%acquisition     = surf%acquisition
   return
   endsubroutine surf2scal
Call graph
surf2scal calls c_f_string
c_f_string calls empty
write_surf calls surf2scal
open_surffile calls surf2scal
save_fe_field calls write_surf
save_ms_field calls write_surf
solve_ms_prob calls save_ms_field
solve_fe_prob calls save_fe_field
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config