test_rough_ms – MUSST
test_rough_ms Subroutine
8 statements
Source File
private subroutine test_rough_ms()
Note
Subroutine to run the rough surface multiscale problem
Arguments
None
Calls
Called by
Contents
Source Code
test_rough_ms
Source Code
   subroutine test_rough_ms
   implicit none
      call init_rough_prob
      call init_ms_prob
      call apply_roughness_MS(ms_fe_f, tab_s)
      call solve_ms_prob
   return
   endsubroutine test_rough_ms
Call graph
test_rough_ms calls solve_ms_prob, init_ms_prob, init_rough_prob, apply_roughness_ms
solve_ms_prob calls save_ms_field, multi_scale_solve_fe_film
init_ms_prob calls multi_scale_create_rect_fe_film
apply_roughness_ms calls apply_roughness
save_ms_field calls empty, ms_fe_f_2_mat, write_surf, init_scal
multi_scale_solve_fe_film calls apply_bc_fe_film_simple, solve_fe_film, convert_matrice_format, multi_scale_assembly_fe_film_reynolds, omp_get_thread_num, solve_syst
multi_scale_create_rect_fe_film calls create_rect_fe_film
solve_fe_film calls apply_bc_fe_film_simple, convert_matrice_format, omp_get_thread_num, solve_syst, assembly_fe_film_reynolds, apply_bc_fe_film
create_rect_fe_film calls create_rect_x_ymesh
convert_matrice_format calls from_elemental_to_assembled
multi_scale_assembly_fe_film_reynolds calls omp_get_thread_num
solve_syst calls factorize_solver, freefact_solver, init_solver, solution_solver, analyse_solver, close_solver
write_surf calls lower, surf2scal, get_unit, scal2surf
init_scal calls empty
factorize_solver calls s_umfpack_di_numeric, ma48_factorize, umfpack_di_free_numeric, dmumps
freefact_solver calls free_superlu, umfpack_di_free_numeric
init_solver calls mpi_init, umfpack_di_defaults, ma48_initialize, init_superlu, mpi_finalize, umfpack_di_report_control, dmumps
surf2scal calls c_f_string
solution_solver calls solv_superlu, s_umfpack_di_solve, ma48_solve, mpi_finalize, dmumps
analyse_solver calls ma48_analyse, prep_superlu, s_umfpack_di_symbolic, dmumps
close_solver calls umfpack_di_report_info, ma48_finalize, umfpack_di_free_numeric, mpi_finalize, umfpack_di_free_symbolic, dmumps, close_superlu
assembly_fe_film_reynolds calls assemble_in_mat_sol, elementary_assembly_fe_film_reynolds
solv_superlu calls prep_superlu, statfree, statinit, destroy_compcol_matrix, dgssvx, destroy_supernode_matrix
s_umfpack_di_numeric calls umfpack_di_numeric
s_umfpack_di_solve calls umfpack_di_solve
umfpack_di_report_info calls c_umfpack_di_report_info
umfpack_di_defaults calls c_umfpack_di_defaults
elementary_assembly_fe_film_reynolds calls compute_prc_tables_reynolds_supg
init_superlu calls set_default_options
c_f_string calls empty
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_report_control calls c_umfpack_di_report_control
prep_superlu calls dcreate_dense_matrix, dcreate_compcol_matrix
s_umfpack_di_symbolic calls umfpack_di_symbolic
close_superlu calls destroy_compcol_matrix, destroy_dense_matrix
umfpack_di_numeric calls c_umfpack_di_numeric
umfpack_di_solve calls c_umfpack_di_solve
umfpack_di_symbolic calls c_umfpack_di_symbolic
compute_prc_tables_reynolds_supg calls ni4_up_2d, length_width_elem, dj4
ni4_up_2d calls ni4_up_1d
run_test calls test_rough_ms
read_config calls run_test
main calls read_config