umfpack_di_defaults – MUSST
umfpack_di_defaults Subroutine
10 statements
Source File
public subroutine umfpack_di_defaults(Control)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
Calls
Called by
Contents
None
Call graph
umfpack_di_defaults calls c_umfpack_di_defaults
init_solver calls umfpack_di_defaults
s_umfpack_di_defaults calls umfpack_di_defaults
umfpack_defaults calls umfpack_di_defaults
solve_syst calls init_solver
umf4cdef calls umfpack_defaults
umf4def calls umfpack_defaults
s_umfpack_defaults calls umfpack_defaults
umf4zdef calls umfpack_defaults
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_fe_film calls solve_syst
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_fe_prob calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
test_bearing_x_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
test_pocket_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
run_test calls test_bearing_x_fe, test_slider_ms, test_pocket_fe, test_rough_fe, test_rough_ms, test_slider_fe, test_bearing_y_fe
main calls run_test