umfpack_report_control – MUSST
umfpack_report_control Subroutine
18 statements
Source File
public subroutine umfpack_report_control(Control, version)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional :: Control(0:UMFPACK_CONTROL-1)
character(len=*), optional :: version
Calls
Called by
Contents
None
Call graph
umfpack_report_control calls umfpack_zi_report_control, umfpack_di_report_control
umfpack_zi_report_control calls c_umfpack_zi_report_control
umfpack_di_report_control calls c_umfpack_di_report_control
s_umfpack_report_control calls umfpack_report_control
umf4cpcon calls umfpack_report_control
umf4pcon calls umfpack_report_control
umf4zpcon calls umfpack_report_control