umfpack_di_symbolic – MUSST
umfpack_di_symbolic Function
39 statements
Source File
public function umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, Symbolic, Control, Info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_row
integer, intent(in) :: n_col
integer, intent(in), target :: Ap(*)
integer, intent(in), target :: Ai(*)
real(kind=r8), intent(in), optional target :: Ax(*)
type(c_ptr), optional :: Symbolic
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), optional target :: Info(0:UMFPACK_INFO-1)
Return Value integer
Calls
Called by
Contents
None
Call graph
umfpack_di_symbolic calls c_umfpack_di_symbolic
s_umfpack_di_symbolic calls umfpack_di_symbolic
umfpack_symbolic calls umfpack_di_symbolic
umfpack_di_operator_csr calls s_umfpack_di_symbolic
umfpack_di_operator_pcsc calls s_umfpack_di_symbolic
umfpack_di_operator_csc calls s_umfpack_di_symbolic
umfpack_di_operator_pcsr calls s_umfpack_di_symbolic
analyse_solver calls s_umfpack_di_symbolic
s_umfpack_symbolic calls s_umfpack_di_symbolic
umf4zsym calls s_umfpack_symbolic, umf4csym_ip, umf4zsym_ip, umf4zsym
umf4csym calls s_umfpack_symbolic, umf4csym_ip, umf4csym
umf4sym_ip calls s_umfpack_symbolic
solve_syst calls analyse_solver
umf4sym calls s_umfpack_symbolic, umf4sym_ip, umf4csym_ip, umf4zsym_ip, umf4sym
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_csc, umfpack_di_operator_pcsr
umf4csym_ip calls s_umfpack_symbolic
umf4zsym_ip calls s_umfpack_symbolic
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config