umfpack_zi_defaults – MUSST
umfpack_zi_defaults Subroutine
10 statements
Source File
public subroutine umfpack_zi_defaults(Control)
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
Calls
Called by
Contents
None
Call graph
umfpack_zi_defaults calls c_umfpack_zi_defaults
umfpack_defaults calls umfpack_zi_defaults
s_umfpack_zi_defaults calls umfpack_zi_defaults
umf4cdef calls umfpack_defaults
umf4zdef calls umfpack_defaults
s_umfpack_defaults calls umfpack_defaults
umf4def calls umfpack_defaults