umfpack_di_free_symbolic – MUSST
umfpack_di_free_symbolic Subroutine
15 statements
Source File
public subroutine umfpack_di_free_symbolic(Symbolic)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), optional :: Symbolic
Calls
Called by
Contents
None
Call graph
umfpack_di_free_symbolic calls c_umfpack_di_free_symbolic
umfpack_di_operator_csr calls umfpack_di_free_symbolic
umfpack_di_operator_pcsc calls umfpack_di_free_symbolic
umfpack_di_operator_csc calls umfpack_di_free_symbolic
umfpack_di_operator_pcsr calls umfpack_di_free_symbolic
close_solver calls umfpack_di_free_symbolic
s_umfpack_di_free_symbolic calls umfpack_di_free_symbolic
umfpack_free_symbolic calls umfpack_di_free_symbolic
s_umfpack_free_symbolic calls umfpack_free_symbolic
umf4zfsym calls umfpack_free_symbolic, umf4zfsym_ip, umf4zfsym
umf4fsym_ip calls umfpack_free_symbolic
solve_syst calls close_solver
umf4cfsym calls umfpack_free_symbolic, umf4cfsym_ip, umf4cfsym
umf4zfsym_ip calls umfpack_free_symbolic
umf4fsym calls umfpack_free_symbolic, umf4fsym_ip, umf4fsym
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_csc, umfpack_di_operator_pcsr
umf4cfsym_ip calls umfpack_free_symbolic
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config