umfpack_di_report_info – MUSST
umfpack_di_report_info Subroutine
17 statements
Source File
public subroutine umfpack_di_report_info(Control, Info)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
real(kind=r8), target :: Info(0:UMFPACK_INFO-1)
Calls
Called by
Contents
None
Call graph
umfpack_di_report_info calls c_umfpack_di_report_info
close_solver calls umfpack_di_report_info
umfpack_report_info calls umfpack_di_report_info
s_umfpack_di_report_info calls umfpack_di_report_info
umf4cpinf calls umfpack_report_info
s_umfpack_report_info calls umfpack_report_info
umf4zpinf calls umfpack_report_info
umf4pinf calls umfpack_report_info
solve_syst calls close_solver
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_fe_prob calls solve_fe_film
test_rough_fe calls solve_fe_prob
test_bearing_x_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
run_test calls test_rough_fe, test_bearing_x_fe, test_pocket_fe, test_bearing_y_fe, test_rough_ms, test_slider_fe, test_slider_ms
main calls run_test