umfpack_di_report_control – MUSST
umfpack_di_report_control Subroutine
15 statements
Source File
public subroutine umfpack_di_report_control(Control)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
real(kind=r8), optional target :: Control(0:UMFPACK_CONTROL-1)
Calls
Called by
Contents
None
Call graph
umfpack_di_report_control calls c_umfpack_di_report_control
init_solver calls umfpack_di_report_control
s_umfpack_di_report_control calls umfpack_di_report_control
umfpack_report_control calls umfpack_di_report_control
solve_syst calls init_solver
s_umfpack_report_control calls umfpack_report_control
umf4cpcon calls umfpack_report_control
umf4pcon calls umfpack_report_control
umf4zpcon calls umfpack_report_control
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_fe_film calls solve_syst
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_fe_prob calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
test_bearing_x_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
test_pocket_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
run_test calls test_bearing_x_fe, test_slider_ms, test_pocket_fe, test_rough_fe, test_rough_ms, test_slider_fe, test_bearing_y_fe
main calls run_test