c_umfpack_di_solve – MUSST
c_umfpack_di_solve Interface
172 statements
Source File
interface
Called by
public function c_umfpack_di_solve(sys, Ap, Ai, Ax, X, B, Numeric, Control, Info) bind(c,name='umfpack_di_solve')
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: sys
type(c_ptr), intent(in), value :: Ap
type(c_ptr), intent(in), value :: Ai
type(c_ptr), intent(in), value :: Ax
type(c_ptr), value :: X
type(c_ptr), intent(in), value :: B
type(c_ptr), intent(in), value :: Numeric
type(c_ptr), value :: Control
type(c_ptr), value :: Info
Return Value integer(kind=c_int)
Call graph
umfpack_di_solve calls c_umfpack_di_solve
s_umfpack_di_solve calls umfpack_di_solve
umfpack_solve calls umfpack_di_solve
umfpack_di_operator_csr calls s_umfpack_di_solve
umfpack_di_operator_pcsc calls s_umfpack_di_solve
umfpack_di_operator_csc calls s_umfpack_di_solve
umfpack_di_operator_pcsr calls s_umfpack_di_solve
solution_solver calls s_umfpack_di_solve
s_umfpack_solve calls s_umfpack_di_solve
umf4sol calls s_umfpack_solve, umf4sol_ip, umf4sol
umf4solr_ip calls s_umfpack_solve
umf4sol_ip calls s_umfpack_solve
solve_syst calls solution_solver
umf4csolr_ip calls s_umfpack_solve
umf4zsolr_ip calls s_umfpack_solve
umf4solr calls s_umfpack_solve, umf4solr_ip, umf4csolr_ip, umf4zsolr_ip, umf4solr
umf4zsolr calls s_umfpack_solve, umf4csolr_ip, umf4zsolr_ip, umf4zsolr
umf4zsol calls s_umfpack_solve
umf4csolr calls s_umfpack_solve, umf4csolr_ip, umf4csolr
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_csc, umfpack_di_operator_pcsr
umf4csol calls s_umfpack_solve
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config