c_umfpack_di_free_numeric – MUSST
c_umfpack_di_free_numeric Interface
172 statements
Source File
interface
Called by
public subroutine c_umfpack_di_free_numeric(Numeric) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: Numeric
Call graph
umfpack_di_free_numeric calls c_umfpack_di_free_numeric
factorize_solver calls umfpack_di_free_numeric
freefact_solver calls umfpack_di_free_numeric
s_umfpack_di_free_numeric calls umfpack_di_free_numeric
umfpack_di_operator_csr calls umfpack_di_free_numeric
umfpack_free_numeric calls umfpack_di_free_numeric
umfpack_di_operator_pcsc calls umfpack_di_free_numeric
umfpack_di_operator_csc calls umfpack_di_free_numeric
umfpack_di_operator_pcsr calls umfpack_di_free_numeric
close_solver calls umfpack_di_free_numeric
operator(.umfpack.) calls umfpack_di_operator_csr, umfpack_di_operator_pcsc, umfpack_di_operator_csc, umfpack_di_operator_pcsr
s_umfpack_free_numeric calls umfpack_free_numeric
umf4cfnum_ip calls umfpack_free_numeric
umf4zfnum_ip calls umfpack_free_numeric
umf4zfnum calls umfpack_free_numeric, umf4zfnum_ip, umf4zfnum
solve_syst calls factorize_solver, freefact_solver, close_solver
umf4cfnum calls umfpack_free_numeric, umf4cfnum_ip, umf4cfnum
umf4fnum calls umfpack_free_numeric, umf4fnum_ip, umf4fnum
umf4fnum_ip calls umfpack_free_numeric
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config