cton – MUSST
cton Interface
3 statements
Source File
public interface cton
Calls
Contents
Module Procedures
ctor_R16P ctor_R8P ctor_R4P ctoi_I8P ctoi_I4P ctoi_I2P ctoi_I1P
Module Procedures
private function ctor_R16P(str, knd) result(n)
The function ctor_R16P converts string to real. This function achieves casting of string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=R16P), intent(in) :: knd
Return Value real(kind=R16P)
private function ctor_R8P(str, knd) result(n)
The function ctor_R8P converts string to real. This function achieves casting of string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=R8P), intent(in) :: knd
Return Value real(kind=R8P)
private function ctor_R4P(str, knd) result(n)
The function ctor_R4P converts string to real. This function achieves casting of string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=R4P), intent(in) :: knd
Return Value real(kind=R4P)
private function ctoi_I8P(str, knd) result(n)
The function ctoi_I8P converts string to integer. This function achieves casting of string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I8P), intent(in) :: knd
Return Value integer(kind=I8P)
private function ctoi_I4P(str, knd) result(n)
The function ctoi_I4P converts string to integer. This function achieves casting of string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I4P), intent(in) :: knd
Return Value integer(kind=I4P)
private function ctoi_I2P(str, knd) result(n)
The function ctoi_I2P converts string to integer. This function achieves casting of string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I2P), intent(in) :: knd
Return Value integer(kind=I2P)
private function ctoi_I1P(str, knd) result(n)
The function ctoi_I1P converts string to integer. This function achieves casting of string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer(kind=I1P), intent(in) :: knd
Return Value integer(kind=I1P)
Call graph
cton calls ctoi_i1p, ctoi_i8p, ctor_r4p, ctoi_i2p, ctor_r8p, ctor_r16p, ctoi_i4p