Destroy_Dense_Matrix – MUSST
Destroy_Dense_Matrix Interface
98 statements
Source File
interface
Called by
private subroutine Destroy_Dense_Matrix(A) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERMATRIX), intent(in) :: A
Call graph
close_superlu calls destroy_dense_matrix
close_solver calls close_superlu
solve_syst calls close_solver
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_fe_film calls solve_syst
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_fe_prob calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
test_bearing_x_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
test_pocket_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_slider_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
run_test calls test_bearing_x_fe, test_slider_ms, test_pocket_fe, test_rough_fe, test_rough_ms, test_slider_fe, test_bearing_y_fe
main calls run_test