set_default_options – MUSST
set_default_options Interface
98 statements
Source File
interface
Called by
private subroutine set_default_options(options) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERLU_OPTIONS_T), intent(inout) :: options
Call graph
init_superlu calls set_default_options
init_solver calls init_superlu
solve_syst calls init_solver
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
solve_fe_prob calls solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
test_slider_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_bearing_y_fe calls solve_fe_prob
test_slider_ms calls solve_ms_prob
test_pocket_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
run_test calls test_slider_fe, test_rough_ms, test_bearing_x_fe, test_bearing_y_fe, test_slider_ms, test_pocket_fe, test_rough_fe
main calls run_test