StatInit – MUSST
StatInit Interface
98 statements
Source File
interface
Called by
private subroutine StatInit(stat) bind(c, name="0")
Arguments
Type Intent Optional Attributes Name
type(SUPERLUSTAT_T), intent(out) :: stat
Call graph
solv_superlu calls statinit
fact_superlu calls statinit
solution_solver calls solv_superlu
solve_syst calls solution_solver
solve_fe_film calls solve_syst
multi_scale_solve_fe_film calls solve_syst, solve_fe_film
elementary_full_domain_fe_film_reynolds calls solve_fe_film
solve_ms_prob calls multi_scale_solve_fe_film
solve_fe_prob calls solve_fe_film
test_slider_ms calls solve_ms_prob
test_bearing_x_fe calls solve_fe_prob
test_rough_ms calls solve_ms_prob
test_bearing_y_fe calls solve_fe_prob
test_rough_fe calls solve_fe_prob
test_pocket_fe calls solve_fe_prob
test_slider_fe calls solve_fe_prob
run_test calls test_slider_ms, test_bearing_x_fe, test_rough_ms, test_bearing_y_fe, test_rough_fe, test_pocket_fe, test_slider_fe
read_config calls run_test
main calls read_config