VTK_VAR_XML – MUSST
VTK_VAR_XML Interface
3 statements
Source File
public interface VTK_VAR_XML
Calls
Contents
Module Procedures
VTK_VAR_XML_SCAL_R8 VTK_VAR_XML_SCAL_R4 VTK_VAR_XML_SCAL_I8 VTK_VAR_XML_SCAL_I4 VTK_VAR_XML_SCAL_I2 VTK_VAR_XML_SCAL_I1 VTK_VAR_XML_VECT_R8 VTK_VAR_XML_VECT_R4 VTK_VAR_XML_VECT_I8 VTK_VAR_XML_VECT_I4 VTK_VAR_XML_VECT_I2 VTK_VAR_XML_VECT_I1 VTK_VAR_XML_LIST_R8 VTK_VAR_XML_LIST_R4 VTK_VAR_XML_LIST_I8 VTK_VAR_XML_LIST_I4 VTK_VAR_XML_LIST_I2 VTK_VAR_XML_LIST_I1
Module Procedures
private function VTK_VAR_XML_SCAL_R8(NC_NN, varname, var) result(E_IO)
Function for saving scalar variable (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R8P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_SCAL_R4(NC_NN, varname, var) result(E_IO)
Function for saving scalar variable (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R4P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_SCAL_I8(NC_NN, varname, var) result(E_IO)
Function for saving scalar variable (I8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I8P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_SCAL_I4(NC_NN, varname, var) result(E_IO)
Function for saving scalar variable (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I4P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_SCAL_I2(NC_NN, varname, var) result(E_IO)
Function for saving scalar variable (I2P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I2P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_SCAL_I1(NC_NN, varname, var) result(E_IO)
Function for saving scalar variable (I1P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I1P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_VECT_R8(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving vectorial variable (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R8P), intent(in) :: varX(1:NC_NN)
real(kind=R8P), intent(in) :: varY(1:NC_NN)
real(kind=R8P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_VECT_R4(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving vectorial variable (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R4P), intent(in) :: varX(1:NC_NN)
real(kind=R4P), intent(in) :: varY(1:NC_NN)
real(kind=R4P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_VECT_I8(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving vectorial variable (I8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I8P), intent(in) :: varX(1:NC_NN)
integer(kind=I8P), intent(in) :: varY(1:NC_NN)
integer(kind=I8P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_VECT_I4(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving vectorial variable (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I4P), intent(in) :: varX(1:NC_NN)
integer(kind=I4P), intent(in) :: varY(1:NC_NN)
integer(kind=I4P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_VECT_I2(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving vectorial variable (I2P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I2P), intent(in) :: varX(1:NC_NN)
integer(kind=I2P), intent(in) :: varY(1:NC_NN)
integer(kind=I2P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_VECT_I1(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving vectorial variable (I1P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I1P), intent(in) :: varX(1:NC_NN)
integer(kind=I1P), intent(in) :: varY(1:NC_NN)
integer(kind=I1P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_LIST_R8(NC_NN, N_COL, varname, var) result(E_IO)
Function for saving list variable (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: N_COL
character(len=*), intent(in) :: varname
real(kind=R8P), intent(in) :: var(1:NC_NN,1:N_COL)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_LIST_R4(NC_NN, N_COL, varname, var) result(E_IO)
Function for saving list variable (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: N_COL
character(len=*), intent(in) :: varname
real(kind=R4P), intent(in) :: var(1:NC_NN,1:N_COL)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_LIST_I8(NC_NN, N_COL, varname, var) result(E_IO)
Function for saving list variable (I8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: N_COL
character(len=*), intent(in) :: varname
integer(kind=I8P), intent(in) :: var(1:NC_NN,1:N_COL)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_LIST_I4(NC_NN, N_COL, varname, var) result(E_IO)
Function for saving list variable (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: N_COL
character(len=*), intent(in) :: varname
integer(kind=I4P), intent(in) :: var(1:NC_NN,1:N_COL)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_LIST_I2(NC_NN, N_COL, varname, var) result(E_IO)
Function for saving list variable (I2P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: N_COL
character(len=*), intent(in) :: varname
integer(kind=I2P), intent(in) :: var(1:NC_NN,1:N_COL)
Return Value integer(kind=I4P)
private function VTK_VAR_XML_LIST_I1(NC_NN, N_COL, varname, var) result(E_IO)
Function for saving list variable (I1P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: N_COL
character(len=*), intent(in) :: varname
integer(kind=I1P), intent(in) :: var(1:NC_NN,1:N_COL)
Return Value integer(kind=I4P)
Call graph
vtk_var_xml calls vtk_var_xml_vect_i8, vtk_var_xml_list_i8, vtk_var_xml_list_r8, vtk_var_xml_vect_i2, vtk_var_xml_vect_i1, vtk_var_xml_scal_i4, vtk_var_xml_list_i2, vtk_var_xml_scal_r4, vtk_var_xml_scal_i2, vtk_var_xml_list_i4, vtk_var_xml_vect_r4, vtk_var_xml_vect_i4, vtk_var_xml_list_i1, vtk_var_xml_scal_i8, vtk_var_xml_vect_r8, vtk_var_xml_scal_i1, vtk_var_xml_scal_r8, vtk_var_xml_list_r4
vtk_var_xml_vect_i8 calls str
vtk_var_xml_list_i8 calls str
vtk_var_xml_list_r8 calls str
vtk_var_xml_vect_i2 calls str
vtk_var_xml_vect_i1 calls str
vtk_var_xml_scal_i4 calls str
vtk_var_xml_list_i2 calls str
vtk_var_xml_scal_r4 calls str
vtk_var_xml_scal_i2 calls str
vtk_var_xml_list_i4 calls str
vtk_var_xml_vect_r4 calls str
vtk_var_xml_vect_i4 calls str
vtk_var_xml_list_i1 calls str
vtk_var_xml_scal_i8 calls str
vtk_var_xml_vect_r8 calls str
vtk_var_xml_scal_i1 calls str
vtk_var_xml_scal_r8 calls str
vtk_var_xml_list_r4 calls str
str calls str_r8p, str_i2p, str_r4p, str_i4p, str_i8p, str_i1p, str_r16p