VTK_GEO_XML – MUSST
VTK_GEO_XML Interface
3 statements
Source File
public interface VTK_GEO_XML
Calls
Contents
Module Procedures
VTK_GEO_XML_STRG_R4 VTK_GEO_XML_STRG_R8 VTK_GEO_XML_RECT_R8 VTK_GEO_XML_RECT_R4 VTK_GEO_XML_UNST_R8 VTK_GEO_XML_UNST_R4 VTK_GEO_XML_CLOSEP
Module Procedures
private function VTK_GEO_XML_STRG_R4(nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z) result(E_IO)
Function for saving mesh; topology = StructuredGrid (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: nx1
integer(kind=I4P), intent(in) :: nx2
integer(kind=I4P), intent(in) :: ny1
integer(kind=I4P), intent(in) :: ny2
integer(kind=I4P), intent(in) :: nz1
integer(kind=I4P), intent(in) :: nz2
integer(kind=I4P), intent(in) :: NN
real(kind=R4P), intent(in) :: X(1:NN)
real(kind=R4P), intent(in) :: Y(1:NN)
real(kind=R4P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_XML_STRG_R8(nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z) result(E_IO)
Function for saving mesh; topology = StructuredGrid (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: nx1
integer(kind=I4P), intent(in) :: nx2
integer(kind=I4P), intent(in) :: ny1
integer(kind=I4P), intent(in) :: ny2
integer(kind=I4P), intent(in) :: nz1
integer(kind=I4P), intent(in) :: nz2
integer(kind=I4P), intent(in) :: NN
real(kind=R8P), intent(in) :: X(1:NN)
real(kind=R8P), intent(in) :: Y(1:NN)
real(kind=R8P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_XML_RECT_R8(nx1, nx2, ny1, ny2, nz1, nz2, X, Y, Z) result(E_IO)
Function for saving mesh; topology = RectilinearGrid (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: nx1
integer(kind=I4P), intent(in) :: nx2
integer(kind=I4P), intent(in) :: ny1
integer(kind=I4P), intent(in) :: ny2
integer(kind=I4P), intent(in) :: nz1
integer(kind=I4P), intent(in) :: nz2
real(kind=R8P), intent(in) :: X(nx1:nx2)
real(kind=R8P), intent(in) :: Y(ny1:ny2)
real(kind=R8P), intent(in) :: Z(nz1:nz2)
Return Value integer(kind=I4P)
private function VTK_GEO_XML_RECT_R4(nx1, nx2, ny1, ny2, nz1, nz2, X, Y, Z) result(E_IO)
Function for saving mesh; topology = RectilinearGrid (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: nx1
integer(kind=I4P), intent(in) :: nx2
integer(kind=I4P), intent(in) :: ny1
integer(kind=I4P), intent(in) :: ny2
integer(kind=I4P), intent(in) :: nz1
integer(kind=I4P), intent(in) :: nz2
real(kind=R4P), intent(in) :: X(nx1:nx2)
real(kind=R4P), intent(in) :: Y(ny1:ny2)
real(kind=R4P), intent(in) :: Z(nz1:nz2)
Return Value integer(kind=I4P)
private function VTK_GEO_XML_UNST_R8(NN, NC, X, Y, Z) result(E_IO)
Function for saving mesh; topology = UnstructuredGrid (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NN
integer(kind=I4P), intent(in) :: NC
real(kind=R8P), intent(in) :: X(1:NN)
real(kind=R8P), intent(in) :: Y(1:NN)
real(kind=R8P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_XML_UNST_R4(NN, NC, X, Y, Z) result(E_IO)
Function for saving mesh; topology = UnstructuredGrid (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NN
integer(kind=I4P), intent(in) :: NC
real(kind=R4P), intent(in) :: X(1:NN)
real(kind=R4P), intent(in) :: Y(1:NN)
real(kind=R4P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_XML_CLOSEP() result(E_IO)
Function for closing mesh block data.
Arguments
None
Return Value integer(kind=I4P)
Call graph
vtk_geo_xml calls vtk_geo_xml_strg_r4, vtk_geo_xml_unst_r4, vtk_geo_xml_unst_r8, vtk_geo_xml_closep, vtk_geo_xml_strg_r8, vtk_geo_xml_rect_r4, vtk_geo_xml_rect_r8
vtk_geo_xml_strg_r4 calls str
vtk_geo_xml_unst_r4 calls str
vtk_geo_xml_unst_r8 calls str
vtk_geo_xml_strg_r8 calls str
vtk_geo_xml_rect_r4 calls str
vtk_geo_xml_rect_r8 calls str
str calls str_i2p, str_r4p, str_i4p, str_i8p, str_r8p, str_i1p, str_r16p