VTK_VAR – MUSST
VTK_VAR Interface
3 statements
Source File
public interface VTK_VAR
Calls
Called by
Contents
Module Procedures
VTK_VAR_SCAL_R8 VTK_VAR_SCAL_R4 VTK_VAR_SCAL_I4 VTK_VAR_VECT_R8 VTK_VAR_VECT_R4 VTK_VAR_VECT_I4 VTK_VAR_TEXT_R8 VTK_VAR_TEXT_R4
Module Procedures
private function VTK_VAR_SCAL_R8(NC_NN, varname, var) result(E_IO)
Function for saving field of scalar variable (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R8P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_SCAL_R4(NC_NN, varname, var) result(E_IO)
Function for saving field of scalar variable (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R4P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_SCAL_I4(NC_NN, varname, var) result(E_IO)
Function for saving field of scalar variable (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I4P), intent(in) :: var(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_VECT_R8(vec_type, NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving field of vectorial variable (R8P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: vec_type
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R8P), intent(in) :: varX(1:NC_NN)
real(kind=R8P), intent(in) :: varY(1:NC_NN)
real(kind=R8P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_VECT_R4(vec_type, NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving field of vectorial variable (R4P).
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: vec_type
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
real(kind=R4P), intent(in) :: varX(1:NC_NN)
real(kind=R4P), intent(in) :: varY(1:NC_NN)
real(kind=R4P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_VECT_I4(NC_NN, varname, varX, varY, varZ) result(E_IO)
Function for saving field of vectorial variable (I4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
character(len=*), intent(in) :: varname
integer(kind=I4P), intent(in) :: varX(1:NC_NN)
integer(kind=I4P), intent(in) :: varY(1:NC_NN)
integer(kind=I4P), intent(in) :: varZ(1:NC_NN)
Return Value integer(kind=I4P)
private function VTK_VAR_TEXT_R8(NC_NN, dimm, varname, textCoo) result(E_IO)
Function for saving texture variable (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: dimm
character(len=*), intent(in) :: varname
real(kind=R8P), intent(in) :: textCoo(1:NC_NN,1:dimm)
Return Value integer(kind=I4P)
private function VTK_VAR_TEXT_R4(NC_NN, dimm, varname, textCoo) result(E_IO)
Function for saving texture variable (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NC_NN
integer(kind=I4P), intent(in) :: dimm
character(len=*), intent(in) :: varname
real(kind=R4P), intent(in) :: textCoo(1:NC_NN,1:dimm)
Return Value integer(kind=I4P)
Call graph
vtk_var calls vtk_var_vect_r8, vtk_var_text_r4, vtk_var_vect_i4, vtk_var_text_r8, vtk_var_scal_i4, vtk_var_scal_r8, vtk_var_scal_r4, vtk_var_vect_r4
vtk_var_vect_r8 calls upper_case
vtk_var_vect_r4 calls upper_case
save_fe_f_vtk calls vtk_var