VTK_GEO – MUSST
VTK_GEO Interface
3 statements
Source File
public interface VTK_GEO
Calls
Called by
Contents
Module Procedures
VTK_GEO_UNST_R8 VTK_GEO_UNST_R4 VTK_GEO_STRP_R8 VTK_GEO_STRP_R4 VTK_GEO_STRG_R8 VTK_GEO_STRG_R4 VTK_GEO_RECT_R8 VTK_GEO_RECT_R4
Module Procedures
private function VTK_GEO_UNST_R8(NN, X, Y, Z) result(E_IO)
Function for saving mesh; topology = UNSTRUCTURED_GRID (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NN
real(kind=R8P), intent(in) :: X(1:NN)
real(kind=R8P), intent(in) :: Y(1:NN)
real(kind=R8P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_UNST_R4(NN, X, Y, Z) result(E_IO)
Function for saving mesh; topology = UNSTRUCTURED_GRID (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: NN
real(kind=R4P), intent(in) :: X(1:NN)
real(kind=R4P), intent(in) :: Y(1:NN)
real(kind=R4P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_STRP_R8(Nx, Ny, Nz, X0, Y0, Z0, Dx, Dy, Dz) result(E_IO)
Function for saving mesh; topology = STRUCTURED_POINTS (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: Nx
integer(kind=I4P), intent(in) :: Ny
integer(kind=I4P), intent(in) :: Nz
real(kind=R8P), intent(in) :: X0
real(kind=R8P), intent(in) :: Y0
real(kind=R8P), intent(in) :: Z0
real(kind=R8P), intent(in) :: Dx
real(kind=R8P), intent(in) :: Dy
real(kind=R8P), intent(in) :: Dz
Return Value integer(kind=I4P)
private function VTK_GEO_STRP_R4(Nx, Ny, Nz, X0, Y0, Z0, Dx, Dy, Dz) result(E_IO)
Function for saving mesh; topology = STRUCTURED_POINTS (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: Nx
integer(kind=I4P), intent(in) :: Ny
integer(kind=I4P), intent(in) :: Nz
real(kind=R4P), intent(in) :: X0
real(kind=R4P), intent(in) :: Y0
real(kind=R4P), intent(in) :: Z0
real(kind=R4P), intent(in) :: Dx
real(kind=R4P), intent(in) :: Dy
real(kind=R4P), intent(in) :: Dz
Return Value integer(kind=I4P)
private function VTK_GEO_STRG_R8(Nx, Ny, Nz, NN, X, Y, Z) result(E_IO)
Function for saving mesh; topology = STRUCTURED_GRID (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: Nx
integer(kind=I4P), intent(in) :: Ny
integer(kind=I4P), intent(in) :: Nz
integer(kind=I4P), intent(in) :: NN
real(kind=R8P), intent(in) :: X(1:NN)
real(kind=R8P), intent(in) :: Y(1:NN)
real(kind=R8P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_STRG_R4(Nx, Ny, Nz, NN, X, Y, Z) result(E_IO)
Function for saving mesh; topology = STRUCTURED_GRID (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: Nx
integer(kind=I4P), intent(in) :: Ny
integer(kind=I4P), intent(in) :: Nz
integer(kind=I4P), intent(in) :: NN
real(kind=R4P), intent(in) :: X(1:NN)
real(kind=R4P), intent(in) :: Y(1:NN)
real(kind=R4P), intent(in) :: Z(1:NN)
Return Value integer(kind=I4P)
private function VTK_GEO_RECT_R8(Nx, Ny, Nz, X, Y, Z) result(E_IO)
Function for saving mesh; topology = RECTILINEAR_GRID (R8P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: Nx
integer(kind=I4P), intent(in) :: Ny
integer(kind=I4P), intent(in) :: Nz
real(kind=R8P), intent(in) :: X(1:Nx)
real(kind=R8P), intent(in) :: Y(1:Ny)
real(kind=R8P), intent(in) :: Z(1:Nz)
Return Value integer(kind=I4P)
private function VTK_GEO_RECT_R4(Nx, Ny, Nz, X, Y, Z) result(E_IO)
Function for saving mesh; topology = RECTILINEAR_GRID (R4P).
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: Nx
integer(kind=I4P), intent(in) :: Ny
integer(kind=I4P), intent(in) :: Nz
real(kind=R4P), intent(in) :: X(1:Nx)
real(kind=R4P), intent(in) :: Y(1:Ny)
real(kind=R4P), intent(in) :: Z(1:Nz)
Return Value integer(kind=I4P)
Call graph
vtk_geo calls vtk_geo_unst_r8, vtk_geo_strg_r8, vtk_geo_strp_r8, vtk_geo_strg_r4, vtk_geo_strp_r4, vtk_geo_rect_r8, vtk_geo_unst_r4, vtk_geo_rect_r4
save_fe_f_vtk calls vtk_geo